animations = {
	{'daps', 'GANGS', 'hndshkfa',-1, false,"Kézfogás",1},
	{'daps2', 'GANGS', 'hndshkca',-1, false,"Kézfogás 2",1},
	{'heil', 'ON_LOOKERS', 'Pointup_in',-1, false,"Tisztelgés",1},
    {'dance', 'DANCING', 'DAN_Right_A',-1, true,"Tánc",1},
	{'dance2', 'DANCING', 'DAN_Down_A',-1, true,"Tánc 2",1},
	{'dance3', 'DANCING', 'dnce_M_d',-1, true,"Tánc 3",1},
	{'strip', 'STRIP', 'strip_D',-1, true,"Tánc 4",1},
	{'strip2', 'STRIP', 'STR_Loop_C',-1, true,"Tánc 5",1},
	{"sit4", "BEACH", "ParkSit_W_loop", -1, true,"Földön ülés",1},
	{"sit5", "BEACH", "ParkSit_M_loop", -1, true,"Széken ülés",2},
	{"lay", "BEACH", "Lay_Bac_Loop", -1, true,"Lazítás",2},
	{"lay2", "BEACH", "sitnwait_Loop_W", -1, true,"Lazítás 2",2},
	{'gsign', 'GHANDS', 'gsign1',-1, false,"Beszélés",2},
	{'gsign2', 'GHANDS', 'gsign2',-1, false,"Beszélés 2"},
	{'gsign3', 'GHANDS', 'gsign3',-1, false,"Beszélés 3"},
	{'gsign4', 'GHANDS', 'gsign4',-1, false,"Beszélés 4"},
	{'gsign5', 'GHANDS', 'gsign5',-1, false,"Beszélés 5"},
	{'rap', 'LOWRIDER', 'RAP_A_Loop',-1, true,"Rap"},
	{'rap2', 'LOWRIDER', 'RAP_B_Loop',-1, true,"Rap 2"},
	{'rap3', 'LOWRIDER', 'RAP_C_Loop',-1, true,"Rap 3"},
	{'cheer', 'STRIP', 'PUN_HOLLER',-1, true,"Újjongás"},
	{'cheer2', 'OTB', 'wtchrace_win',-1, true,"Újjongás 2"},
	{'cheer3', 'RIOT', 'RIOT_shout',-1, true,"Szurkolás"},
	{'fixcar', 'CAR', 'Fixn_Car_loop',-1, true,"Szerelés (Hanyatt)"},
	{'startrace', 'CAR', 'flag_drop',-1, false,"Verseny indítása"},
	{'carchat', 'CAR_CHAT', 'car_talkm_loop',-1, true,"Beszélés autónál"},
	{'carphone', 'CAR_CHAT', 'carfone_loopA',-1, true,"Beszélés telefonon (Autóban)"},
	{'carphone2', 'CAR_CHAT', 'carfone_loopB',-1, true,"Beszélés telefonon 2 (Autóban)"},
	{'fixing', 'BOMBER', 'BOM_Plant_Loop',-1, true,"Szerelés"}, 
	{"crack", "crack", "crckidle1", -1, true,"Rosszúl lét"},
	{"crack2", "crack", "crckidle2", -1, true,"Rosszúl lét 2"},
	{"crack3", "crack", "crckidle3", -1, true,"Rosszúl lét 3"},
	{"crack4", "crack", "crckidle4", -1, true,"Rosszúl lét 4"},
	{'leanleft', 'MISC', 'Plyrlean_loop', -1, true,"Falnak dőlés (oldalasan)"},
	{"copaway", "police", "coptraf_away", -1, true,"Közlekedés irányítás (Várj)"},
	{"copcome", "police", "CopTraf_Come", -1, true,"Közlekedés irányítás (Gyere)"},
	{"copleft", "police", "CopTraf_Left", -1, true,"Közlekedés irányítás (Balra)"},
	{"copstop", "police", "CopTraf_Stop", -1, true,"Közlekedés irányítás (Álj)"},
	{'shake', 'COP_AMBIENT', 'Coplook_shake',-1, false,"Várakozás"},
	{'lean', 'GANGS', 'leanIDLE',-1, false,"Falnak dőlés (Háttal)"},
	{'idle', 'DEALER', 'DEALER_IDLE_01',-1, false,"Várakozás 2"},
	{'idle2', 'New_Dealer', 'DEALER_IDLE',-1, false,"Várakozás 2"},
	{"wait", "COP_AMBIENT", "Coplook_loop", -1, true,"Várakozás 3"},
	{'tired', 'FAT', 'idle_tired',-1, true,"Fáradt"},
	{'fallfront', 'ped', 'FLOOR_hit_f',-1, false,"Földön fekvés (Hanyatt)"},
	{'fall', 'ped', 'FLOOR_hit',-1, false,"Földön fekvés (Háttal)"},
	{"think", "COP_AMBIENT", "Coplook_think", -1, true,"Gondolkozás"},
	{'crouch', 'CAMERA', 'camstnd_to_camcrch',-1, false,"Letérdelés"},
	{'shocked', 'ON_LOOKERS', 'panic_loop',-1, true,"Meglepődött"},
	{'cover', 'ped', 'duck_cower',-1, true,"Gugolás"},
	{'smoke', 'GANGS', 'smkcig_prtl',-1, true,"Cigizés"},
	{'smoke2', 'SMOKING', 'M_smkstnd_loop',-1, true,"Cigizés 2"},
	{'smoke3', 'LOWRIDER', 'M_smkstnd_loop',-1, true,"Cigizés 3"},
	{'smokelean', 'LOWRIDER', 'M_smklean_loop',-1, true,"Cigézés a falnak dőlve (Háttal)"},
	{'lightup', 'SMOKING', 'M_smk_in',-1, false,"Rágyújtás"},
	{'drag', 'SMOKING', 'M_smk_drag',-1, false,"Szívás"},
	{"sit", "ped", "SEAT_idle", -1, true,"Széken ülés 2"},
	{"sit2", "FOOD", "FF_Sit_Look", -1, true,"Földön ülés"},
	{"sit3", "Attractors", "Stepsit_loop", -1, true,"Ülés valaminek támaszkodva"},
	{"sit4", "BEACH", "ParkSit_W_loop", -1, true,"Ülés a földön oldalvást"},
	{"sit5", "BEACH", "ParkSit_M_loop", -1, true,"Ülés valaminek támaszkodva háttal"},
	{"aim", "SHOP", "ROB_Loop_Threat", -1, true,"Célzás"},
	{"aim2", "ped", "ARRESTgun", -1, false,"Célzás 2"},
	{'hailtaxi', 'MISC', 'Hiker_Pose',-1, false,"Taxi hívás"},
	{'hailcab', 'MISC', 'Hiker_Pose',-1, false,"Stoppolás"},
	{'crouchcome', 'CAMERA', 'camcrch_cmon', -1, false,"Térdelés közben mutogatás"},
	{'fu', 'RIOT', 'RIOT_FUKU',-1, false,"Bemutatás"},
	{'fu2', 'ped', 'fucku',-1, false,"Fenyítés"},
	{'beg', 'SHOP', 'SHP_Rob_React',-1, false,"Védekezés"},
	{'what', 'RIOT', 'RIOT_ANGRY',-1, false,"Keménykedés"},
	{'photograph', 'CAMERA', 'picstnd_take',-1, true,"Fényképezés"},
	{'mourn', 'GRAVEYARD', 'mrnM_loop',-1, true,"Gyászolás"},
	{'cry', 'GRAVEYARD', 'mrnF_loop',-1, true,"Sírás"},
	{'puke', 'FOOD', 'EAT_Vomit_P',-1, false,"Hányás"},
	{'laugh', 'RAPPING', 'Laugh_01',-1, true,"Nevetés"},
	{'plant', 'BOMBER', 'BOM_Plant',-1, false,"Bomba telepítés"},
	{'grab', 'CARRY', 'liftup',-1, false,"Felvétel a földről"},
	{'putdown', 'CARRY', 'putdwn',-1, false,"Lerakás a földre"},
	{'cpr', 'medic', 'cpr',-1, false,"Újraéleszt"},
	{'slapass', 'SWEET', 'sweet_ass_slap',-1, false,"Rácsapás valakinek a fenekére"},
	{'bitchslap', 'MISC', 'bitchslap',-1, false,"Pofozás"},
	{'shove', 'GANGS', 'shake_carSH',-1, false,"Nekifeszülés valaminek (Gugolva)"},
	{'dive', 'ped', 'EV_dive',-1, false,"Bukfenc (Ugrásból)"},
	{'roadcross', 'ped', 'roadcross',-1, true,"Szétnézés az úton"},
	{'roadcross2', 'ped', 'roadcross_female',-1, true,"Szétnézés az úton 2"},
    {'roadcross3', 'ped', 'roadcross_gang',-1, true,"Szétnézés az úton 3"},
	{'handsup', 'New_Ped', 'handsup',-1, false,"Kéz feltevés"},
	{'handchin','block','HandPlant',-1, false,"Kézenállás"},
} 
