animations = {
    {'aduty', 'GANGS', 'hndshkfa',-1, false,"Admindutyba lépés.",1},
    {'nearbyvehicle', 'GANGS', 'hndshkfa',-1, false,"Jármű ID-k megtekintése.",1},
    {'a', 'GANGS', 'hndshkfa',-1, false,"Adminchat.",1},
    {'as', 'GANGS', 'hndshkfa',-1, false,"Adminsegéd chat.",1},
	{'asegit', 'GANGS', 'hndshkfa',-1, false,"Játékos felszedése halálból.",1},
	{'goto', 'GANGS', 'hndshkfa',-1, false,"Teleoportálás játékoshoz.",1},
	{'spec', 'GANGS', 'hndshkfa',-1, false,"Játékos megfigyelése.",1},
	{'stats', 'GANGS', 'hndshkfa',-1, false,"Játékos információi lekérése.",1},
	{'vá', 'GANGS', 'hndshkfa',-1, false,"Játékos PM-re válaszolás.",1},
	{'gethere', 'GANGS', 'hndshkfa',-1, false,"Játékos magadhoz teleportálása.",1},
	{'setskin', 'GANGS', 'hndshkfa',-1, false,"Skin beállítása.",1},
	{'kick', 'GANGS', 'hndshkfa',-1, false,"Játékos kirúgása a szerverről.",1},
	{'ajail', 'GANGS', 'hndshkfa',-1, false,"Játékos börtönbe helyezése.",1},
	{'ojail', 'GANGS', 'hndshkfa',-1, false,"Játékos börtönbe helyezés. (Offline).",1},
	{'unjail', 'GANGS', 'hndshkfa',-1, false,"Játékos kivétele a börtönből.",1},
	{'sethp', 'GANGS', 'hndshkfa',-1, false,"Életerő adása.",1},
	{'setarmor', 'GANGS', 'hndshkfa',-1, false,"Páncél szint adása.",1},
	{'setthirsty', 'GANGS', 'hndshkfa',-1, false,"Ital szint adása.",1},
	{'sethunger', 'GANGS', 'hndshkfa',-1, false,"Étel szint adása.",1},
	{'vhspawn', 'GANGS', 'hndshkfa',-1, false,"Városházára spawnolja a játékost.",1},
	{'fix', 'GANGS', 'hndshkfa',-1, false,"Jármű megjavítása.",1},
	{'gotopos', 'GANGS', 'hndshkfa',-1, false,"X,Y,Z Pozícióhoz teleportálás.",1},
	{'vanish', 'GANGS', 'hndshkfa',-1, false,"Láthatatlan leszel.",1},
	{'asay', 'GANGS', 'hndshkfa',-1, false,"Admin felhívás.",1},
	{'freeze', 'GANGS', 'hndshkfa',-1, false,"Játékos lefagyasztása.",1},
	{'unfreeze', 'GANGS', 'hndshkfa',-1, false,"Játékos kiolvasztása.",1},
	{'hospitalspawn', 'GANGS', 'hndshkfa',-1, false,"Kórházhoz spawnolás.",1},
	{'togachat', 'GANGS', 'hndshkfa',-1, false,"Adminchat kikapcsolása.",1},
	{'mark', 'GANGS', 'hndshkfa',-1, false,"Mark lehelyezése.",1},
	{'gotomark', 'GANGS', 'hndshkfa',-1, false,"Markhoz teleportálás",1},
	{'listmark', 'GANGS', 'hndshkfa',-1, false,"Markok listázása.",1},
	{'delmark', 'GANGS', 'hndshkfa',-1, false,"Mark törlése.",1},
	{'sgoto', 'GANGS', 'hndshkfa',-1, false,"Halk teleportálás.",1},
	{'ban', 'GANGS', 'hndshkfa',-1, false,"Játékos kitiltása a szerverről.",1},
	{'oban', 'GANGS', 'hndshkfa',-1, false,"Játékos kitiltása Offline.",1},
	{'unban', 'GANGS', 'hndshkfa',-1, false,"Játékos kitiltás feloldása.",1},
	{'changename', 'GANGS', 'hndshkfa',-1, false,"Játékos nevének megváltoztatása.",1},
	{'sethelperlevel', 'GANGS', 'hndshkfa',-1, false,"Adminsegéd adása.",1},
	{'setalevel', 'GANGS', 'hndshkfa',-1, false,"Játékos adminszintjének megváltoztatása.",1},
	{'setanick', 'GANGS', 'hndshkfa',-1, false,"Játékos adminnevének megváltoztatása.",1},
	{'setplayergroup', 'GANGS', 'hndshkfa',-1, false,"Játékos frakcióba helyezése.",1},
	{'setgroupleader', 'GANGS', 'hndshkfa',-1, false,"Játékos frakcióba leader adása.",1},
	{'setmoney', 'GANGS', 'hndshkfa',-1, false,"Játékos pénzének beállítása.",1},
	{'setpp', 'GANGS', 'hndshkfa',-1, false,"Játékos PrémiumPontjának beállítása.",1},
	{'createvehicle', 'GANGS', 'hndshkfa',-1, false,"Jármű létrehozása.",1},
	{'createsafe', 'GANGS', 'hndshkfa',-1, false,"Széf létrehozása.",1},
	{'movesafe', 'GANGS', 'hndshkfa',-1, false,"Széf mozgatása.",1},
	{'delsafe', 'GANGS', 'hndshkfa',-1, false,"Széf törlése.",1},
	{'nearbysafe', 'GANGS', 'hndshkfa',-1, false,"Széf ID-k megnézése.",1},



} 
