--setVehicleHandling ( element theVehicle, string property, var value )

-- Anthony Script -- 2015.09.21. 22:51
-- Felhasznált weboldal: http://gta.wikia.com/wiki/Handling.cfg/GTASA --

--alapcuccos--
--setVehicleHandling(veh, "mass", 2600)
--setVehicleHandling(veh, "turnMass", 6333.3)
--setVehicleHandling(veh, "dragCoeff",2.0)
--setVehicleHandling(veh, "centerOfMass", { 0.0, 0.0, -0.2})
--setVehicleHandling(veh, "percentSubmerged", 80)
--setVehicleHandling(veh, "tractionMultiplier", 0.95)
--setVehicleHandling(veh, "tractionLoss", 0.70)
--setVehicleHandling(veh, "tractionBias", 0.46)
--setVehicleHandling(veh, "numberOfGears", 5)
--setVehicleHandling(veh, "maxVelocity", 860)  -- végsebesség 
--setVehicleHandling(veh, "engineAcceleration", 15)   -- Gyorsulás 
--setVehicleHandling(veh, "engineInertia", 30)
--setVehicleHandling(veh, "driveType", "FWD")
--setVehicleHandling(veh, "engineType", "petrol")
--setVehicleHandling(veh, "brakeDeceleration", 3.0)   -- fékezés 
--setVehicleHandling(veh, "brakeBias", 0.80)
--setVehicleHandling(veh, "ABS", false)
--setVehicleHandling(veh, "steeringLock", 44.0)
--setVehicleHandling(veh, "suspensionForceLevel", 1.5)
--setVehicleHandling(veh, "suspensionDamping", 0.07)
--setVehicleHandling(veh, "suspensionHighSpeedDamping", 2.0)
--setVehicleHandling(veh, "suspensionUpperLimit", 0.20)
--setVehicleHandling(veh, "suspensionLowerLimit", -0.12)
--setVehicleHandling(veh, "suspensionFrontRearBias", 0.45)
--setVehicleHandling(veh, "suspensionAntiDiveMultiplier", 0.0)
--setVehicleHandling(veh, "seatOffsetDistance", 0.2) 
--setVehicleHandling(veh, "collisionDamageMultiplier", 0.43)
--setVehicleHandling(veh, "monetary", 20000)
--setVehicleHandling(veh, "modelFlags", 1)
--setVehicleHandling(veh, "handlingFlags", 1)
--setVehicleHandling(veh, "headLight", 0)
--setVehicleHandling(veh, "tailLight", 3)
--setVehicleHandling(veh, "animGroup", 13)
--alapcuccos

--addEvent("UpdateHandling",true);

function loadHandling(v)	
		if getVehicleModel(v) == 480 then 									-- Comet
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 3000)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 0.9)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 5)
			setVehicleHandling(v, "maxVelocity", 184)
			setVehicleHandling(v, "engineAcceleration", 50)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.04)
		end
		if getVehicleModel(v) == 424 then 									-- Comet
				setVehicleHandling(v, "maxVelocity", 500)
				setVehicleHandling(v, "engineAcceleration", 60.5)
				setVehicleHandling(v, "engineInertia", 100)
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 390.0)
				setVehicleHandling(v, "ABS", true)
				setVehicleHandling(v, "driveType", "awd")
				setVehicleHandling(v, "steeringLock", 35.0)
				setVehicleHandling(v, "tractionMultiplier", 1.51)
                setVehicleHandling(v, "tractionLoss", 0.93)
                setVehicleHandling(v, "tractionBias", 0.36)
				setVehicleHandling(v, "centerOfMass", { 0.0, -0.3, -0.3})
				setVehicleHandling(v, "suspensionDamping", 0.2)
				setVehicleHandling(v, "suspensionForceLevel", 0.75)
				setVehicleHandling(v, "mass", 1550)
		end	
		if getVehicleModel(v) == 434 then
				setVehicleHandling(v, "maxVelocity", 248)
				setVehicleHandling(v, "engineAcceleration", 64.5)
				setVehicleHandling(v, "engineInertia", 46.0)
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 390.0)
				setVehicleHandling(v, "ABS", true)
				setVehicleHandling(v, "driveType", "awd")
				setVehicleHandling(v, "steeringLock", 35.0)
				setVehicleHandling(v, "tractionMultiplier", 1.51)
                setVehicleHandling(v, "tractionLoss", 0.93)
                setVehicleHandling(v, "tractionBias", 0.36)
				setVehicleHandling(v, "centerOfMass", { 0.0, -0.3, -0.3})
				setVehicleHandling(v, "suspensionDamping", 0.2)
				setVehicleHandling(v, "suspensionForceLevel", 1.05)
				setVehicleHandling(v, "mass", 1550)
		end		
		if getVehicleModel(v) == 494 then 									-- Hotring
			setVehicleHandling(v, "maxVelocity", 240)
			setVehicleHandling(v, "engineAcceleration", 67)
			setVehicleHandling(v, "engineInertia", 50.0)
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 420.0)
			setVehicleHandling(v, "ABS", true)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "steeringLock", 35.0)
			setVehicleHandling(v, "tractionMultiplier", 1.05)
			setVehicleHandling(v, "tractionLoss", 0.85)
			setVehicleHandling(v, "tractionBias", 0.49)
			setVehicleHandling(v, "suspensionForceLevel", 1.2)
			setVehicleHandling(v, "centerOfMass", { 0.0, -0.15, -0.3})
			setVehicleHandling(v, "dragCoeff",1.0)
			setVehicleHandling(v, "suspensionHighSpeedDamping", 0.1)
			setVehicleHandling(v, "suspensionLowerLimit", -0.10)
		end

			--Perennial
		if getVehicleModel(v) == 404 then
				setVehicleHandling(v, "mass", 1200)
				setVehicleHandling(v, "turnMass", 3000)
				setVehicleHandling(v, "dragCoeff", 2.5)
				setVehicleHandling(v, "centerOfMass", { 0, 0.1, 0 } )
				setVehicleHandling(v, "percentSubmerged", 70)
				setVehicleHandling(v, "tractionMultiplier", 0.7)
				setVehicleHandling(v, "tractionLoss", 0.9)
				setVehicleHandling(v, "tractionBias", 0.48)
				setVehicleHandling(v, "numberOfGears", 5)
				setVehicleHandling(v, "maxVelocity", 170)
				setVehicleHandling(v, "engineAcceleration", 22)
				setVehicleHandling(v, "engineInertia", 10)
				setVehicleHandling(v, "driveType", "fwd")
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 200)
				setVehicleHandling(v, "ABS", false)
				setVehicleHandling(v, "steeringLock", 30)
				setVehicleHandling(v, "suspensionForceLevel", 1.4)
				setVehicleHandling(v, "suspensionDamping", 0.1)
				setVehicleHandling(v, "suspensionHighSpeedDamping", 0)
				setVehicleHandling(v, "suspensionUpperLimit", 0.37)
				setVehicleHandling(v, "suspensionLowerLimit", -0.17)
				setVehicleHandling(v, "suspensionFrontRearBias", 0.5)
				setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0)
				setVehicleHandling(v, "seatOffsetDistance", 0.2)
				setVehicleHandling(v, "collisionDamageMultiplier", 0.6)
				setVehicleHandling(v, "modelFlags", 0x40000000)
				setVehicleHandling(v, "handlingFlags", 0x10000002)
		end
			-- Solair
		if getVehicleModel(v) == 458 then
				setVehicleHandling(v, "mass", 1600)
				setVehicleHandling(v, "turnMass", 3000)
				setVehicleHandling(v, "dragCoeff", 1.8)
				setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
				setVehicleHandling(v, "percentSubmerged", 75)
				setVehicleHandling(v, "tractionMultiplier", 0.9)
				setVehicleHandling(v, "tractionLoss", 0.9)
				setVehicleHandling(v, "tractionBias", 0.497)
				setVehicleHandling(v, "numberOfGears", 5)
				setVehicleHandling(v, "maxVelocity", 156)
				setVehicleHandling(v, "engineAcceleration", 30)
				setVehicleHandling(v, "engineInertia", 50)
				setVehicleHandling(v, "driveType", "awd")
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 50)
				setVehicleHandling(v, "ABS", false)
				setVehicleHandling(v, "steeringLock", 35)
				setVehicleHandling(v, "monetary", 25000)
				setVehicleHandling(v, "modelFlags", 0x40000001)
				setVehicleHandling(v, "handlingFlags", 0x10308803)
				setVehicleHandling(v, "headLight", 0)
				setVehicleHandling(v, "tailLight", 1)
				setVehicleHandling(v, "animGroup", 0)
				setVehicleHandling(v, "suspensionUpperLimit", 0.28)
				setVehicleHandling(v, "suspensionLowerLimit", -0.1)
		end		
			-- Landstalker -
		if getVehicleModel(v) == 400 then
				setVehicleHandling(v, "maxVelocity", 164)
				setVehicleHandling(v, "engineAcceleration", 25.5)
				setVehicleHandling(v, "engineInertia", 50.0)
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "dragCoeff",2.0)
				setVehicleHandling(v, "brakeDeceleration", 500.0)
				setVehicleHandling(v, "ABS", true)
				setVehicleHandling(v, "steeringLock", 35.0)
				setVehicleHandling(v, "driveType", "awd")
				setVehicleHandling(v, "tractionMultiplier", 0.9)
                setVehicleHandling(v, "tractionLoss", 0.8)
                setVehicleHandling(v, "tractionBias", 0.5)
				setVehicleHandling(v, "suspensionDamping", 0.75)
				setVehicleHandling(v, "suspensionUpperLimit", 0.45) --lengéscsillapító, minél magasabb anál lágyabb
				setVehicleHandling(v, "suspensionLowerLimit", -0.10)
		end		
		if getVehicleModel(v) == 502 then
				setVehicleHandling(v, "maxVelocity", 281)
				setVehicleHandling(v, "engineAcceleration", 135)
				setVehicleHandling(v, "engineInertia", 50.0)
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 390.0)
				setVehicleHandling(v, "ABS", true)
				setVehicleHandling(v, "driveType", "awd")
				setVehicleHandling(v, "steeringLock", 35.0)
				setVehicleHandling(v, "tractionMultiplier", 1.38)
                setVehicleHandling(v, "tractionLoss", 0.69)
                setVehicleHandling(v, "tractionBias", 0.49)
				setVehicleHandling(v, "suspensionForceLevel", 0.70)
				setVehicleHandling(v, "centerOfMass", { 0.0, 0.3, -0.3})
				setVehicleHandling(v, "dragCoeff",1.0)
				setVehicleHandling(v, "suspensionHighSpeedDamping", 0.1)
		end		
		if getVehicleModel(v) == 503 then
				setVehicleHandling(v, "maxVelocity", 313)
				setVehicleHandling(v, "engineAcceleration", 89)
				setVehicleHandling(v, "engineInertia", 59.0)
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 390.0)
				setVehicleHandling(v, "ABS", true)
				setVehicleHandling(v, "driveType", "awd")
				setVehicleHandling(v, "steeringLock", 35.0)
				setVehicleHandling(v, "tractionMultiplier", 1.51)
                setVehicleHandling(v, "tractionLoss", 0.93)
                setVehicleHandling(v, "tractionBias", 0.36)
				setVehicleHandling(v, "centerOfMass", { 0.0, 0.1, -0.3})
				setVehicleHandling(v, "suspensionDamping", 0.2)
				setVehicleHandling(v, "suspensionForceLevel", 0.75)
				setVehicleHandling(v, "mass", 1550)
		 end		
			  -- Rancher
		 if getVehicleModel(v) == 489 then
				setVehicleHandling(v, "maxVelocity", 182)
				setVehicleHandling(v, "engineAcceleration", 50.5)
				setVehicleHandling(v, "engineInertia", 50.0)
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "dragCoeff",2.0)
				setVehicleHandling(v, "brakeDeceleration", 500.0)
				setVehicleHandling(v, "ABS", true)
				setVehicleHandling(v, "steeringLock", 35.0)
				setVehicleHandling(v, "driveType", "awd")
				setVehicleHandling(v, "tractionMultiplier", 1.4)
                setVehicleHandling(v, "tractionLoss", 0.8)
                setVehicleHandling(v, "tractionBias", 0.5)
				setVehicleHandling(v, "suspensionDamping", 0.75)
				setVehicleHandling(v, "suspensionForceLevel", 3)
				setVehicleHandling(v, "suspensionUpperLimit", 0.45) --lengéscsillapító, minél magasabb anál lágyabb
				setVehicleHandling(v, "suspensionLowerLimit", -0.10)
		end
			  -- Mesa
		 if getVehicleModel(v) == 500 then
				setVehicleHandling(v, "maxVelocity", 139)
				setVehicleHandling(v, "engineAcceleration", 24.5)
				setVehicleHandling(v, "ABS", true)
				setVehicleHandling(v, "driveType", "awd")
		end	
			  -- Mesa
		 if getVehicleModel(v) == 470 then
				setVehicleHandling(v, "maxVelocity", 180)
				setVehicleHandling(v, "engineAcceleration", 30.5)
				setVehicleHandling(v, "ABS", true)
				setVehicleHandling(v, "driveType", "awd")
		end			
			  -- Rancher
		 if getVehicleModel(v) == 505 then
				setVehicleHandling(v, "maxVelocity", 172)
				setVehicleHandling(v, "engineAcceleration", 50.5)
				setVehicleHandling(v, "engineInertia", 50.0)
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "dragCoeff",2.0)
				setVehicleHandling(v, "brakeDeceleration", 500.0)
				setVehicleHandling(v, "ABS", true)
				setVehicleHandling(v, "steeringLock", 35.0)
				setVehicleHandling(v, "driveType", "awd")
				setVehicleHandling(v, "tractionMultiplier", 1.4)
                setVehicleHandling(v, "tractionLoss", 0.8)
                setVehicleHandling(v, "tractionBias", 0.5)
				setVehicleHandling(v, "suspensionDamping", 0.75)
				setVehicleHandling(v, "suspensionForceLevel", 3)
				setVehicleHandling(v, "suspensionUpperLimit", 0.45) --lengéscsillapító, minél magasabb anál lágyabb
				setVehicleHandling(v, "suspensionLowerLimit", -0.10)
		end		
			  -- FreeWay - x
		if getVehicleModel(v) == 463 then
				setVehicleHandling(v, "maxVelocity", 151)
				setVehicleHandling(v, "engineAcceleration", 17.0)
				setVehicleHandling(v, "engineInertia", 5.0)
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "driveType", "rwd")
				setVehicleHandling(v, "steeringLock", 35.0)
				setVehicleHandling(v, "tractionMultiplier", 1.1)
                setVehicleHandling(v, "tractionLoss", 1.8)
                setVehicleHandling(v, "tractionBias", 0.48)
				setVehicleHandling(v, "brakeDeceleration", 15.0)
				setVehicleHandling(v, "centerOfMass", { 0.0, 0.0, -0.1})
				setVehicleHandling(v, "dragCoeff",0.0)
				setVehicleHandling(v, "modelFlags", 10000)
                setVehicleHandling(v, "handlingFlags", 1002000)
		end	
		
			  -- NRG-500 - x
		if getVehicleModel(v) == 522 then
				setVehicleHandling(v, "maxVelocity", 184)
				setVehicleHandling(v, "engineAcceleration", 36.0)
				setVehicleHandling(v, "engineInertia", 5.0)
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "driveType", "rwd")
				setVehicleHandling(v, "steeringLock", 35.0)
				setVehicleHandling(v, "tractionMultiplier", 1.8)
                setVehicleHandling(v, "tractionLoss", 1.15)
                setVehicleHandling(v, "tractionBias", 0.5)
				setVehicleHandling(v, "brakeDeceleration", 19.0)
				setVehicleHandling(v, "centerOfMass", { 0.0, 0.0, -0.09})
				setVehicleHandling(v, "dragCoeff",0.0)
		end		
			  -- PCJ-600 - x
		if getVehicleModel(v) == 461 then
				setVehicleHandling(v, "maxVelocity", 154)
				setVehicleHandling(v, "engineAcceleration", 26.0)
				setVehicleHandling(v, "engineInertia", 5.0)
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "driveType", "rwd")
				setVehicleHandling(v, "steeringLock", 35.0)
				setVehicleHandling(v, "tractionMultiplier", 1.8)
                setVehicleHandling(v, "tractionLoss", 1.15)
                setVehicleHandling(v, "tractionBias", 0.5)
				setVehicleHandling(v, "brakeDeceleration", 10.0)
				setVehicleHandling(v, "centerOfMass", { 0.0, 0.0, -0.09})
				setVehicleHandling(v, "dragCoeff",0.0)
		end		
			  -- BF-400 - x
		if getVehicleModel(v) == 581 then
			    setVehicleHandling(v, "maxVelocity", 179)
				setVehicleHandling(v, "engineAcceleration", 35.0)
				setVehicleHandling(v, "engineInertia", 5.0)
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "driveType", "rwd")
				setVehicleHandling(v, "steeringLock", 35.0)
				setVehicleHandling(v, "tractionMultiplier", 1.8)
                setVehicleHandling(v, "tractionLoss", 1.15)
                setVehicleHandling(v, "tractionBias", 0.5)
				setVehicleHandling(v, "brakeDeceleration", 19.0)
				setVehicleHandling(v, "centerOfMass", { 0.0, 0.0, -0.09})
				setVehicleHandling(v, "dragCoeff",0.0) 
				setVehicleHandling(v, "ABS", false)
				setVehicleHandling(v, "driveType", "awd")				
				
		end	
			-- Ambulan
			if getVehicleModel(v) == 416 then
				setVehicleHandling(v, "mass", 2600)
				setVehicleHandling(v, "turnMass", 7000)
				setVehicleHandling(v, "dragCoeff", 1.7)
				setVehicleHandling(v, "centerOfMass", { 0, 0, -0.1 } )
				setVehicleHandling(v, "percentSubmerged", 90)
				setVehicleHandling(v, "tractionMultiplier", 0.85)
				setVehicleHandling(v, "tractionLoss", 0.8)
				setVehicleHandling(v, "tractionBias", 0.47)
				setVehicleHandling(v, "numberOfGears", 5)
				setVehicleHandling(v, "maxVelocity", 184)
				setVehicleHandling(v, "engineAcceleration", 24)
				setVehicleHandling(v, "engineInertia", 40)
				setVehicleHandling(v, "driveType", "awd")
				setVehicleHandling(v, "engineType", "diesel")
				setVehicleHandling(v, "brakeDeceleration", 50)
				setVehicleHandling(v, "ABS", false)
				setVehicleHandling(v, "steeringLock", 35)
				setVehicleHandling(v, "suspensionForceLevel", 1)
				setVehicleHandling(v, "suspensionDamping", 0.07)
				setVehicleHandling(v, "suspensionHighSpeedDamping", 0)
				setVehicleHandling(v, "suspensionUpperLimit", 0.4)
				setVehicleHandling(v, "suspensionLowerLimit", -0.25)
				setVehicleHandling(v, "suspensionFrontRearBias", 0.5)
				setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0)
				setVehicleHandling(v, "seatOffsetDistance", 0.58)
				setVehicleHandling(v, "collisionDamageMultiplier", 0.33)
				setVehicleHandling(v, "modelFlags", 0x4001)
				setVehicleHandling(v, "handlingFlags", 0x10100006)
		    end	
			-- PD motor
			if getVehicleModel(v) == 523 then
				setVehicleHandling(v, "maxVelocity", 230)
				setVehicleHandling(v, "engineAcceleration", 49.0)
				setVehicleHandling(v, "engineInertia", 5.0)
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "driveType", "rwd")
				setVehicleHandling(v, "steeringLock", 35.0)
				setVehicleHandling(v, "tractionMultiplier", 1.8)
                setVehicleHandling(v, "tractionLoss", 1.15)
                setVehicleHandling(v, "tractionBias", 0.5)
				setVehicleHandling(v, "brakeDeceleration", 19.0)
				setVehicleHandling(v, "centerOfMass", { 0.0, 0.0, -0.09})
				setVehicleHandling(v, "dragCoeff",0.0)
			 end	
				
			 -- Glendale - x
			 if getVehicleModel(v) == 466 then
				setVehicleHandling(v, "maxVelocity", 156)
				setVehicleHandling(v, "engineAcceleration", 16.5)
				setVehicleHandling(v, "engineInertia", 47.0)
			 end	
			 				
			 -- asd- x
			 if getVehicleModel(v) == 456 then
				setVehicleHandling(v, "suspensionForceLevel", 0.5)
			 end

			 -- Hermes - x
			 if getVehicleModel(v) == 474 then
				setVehicleHandling(v, "maxVelocity", 156)
				setVehicleHandling(v, "engineAcceleration", 17.5)
				setVehicleHandling(v, "engineInertia", 48.0)
			 end	
			 -- Esperanto - x
			 if getVehicleModel(v) == 419 then
				setVehicleHandling(v, "maxVelocity", 140)
				setVehicleHandling(v, "engineAcceleration", 19.0)
				setVehicleHandling(v, "engineInertia", 50.0)
			 end	
			 -- Buccaneer - x
			 if getVehicleModel(v) == 518 then
				 setVehicleHandling(v, "maxVelocity", 170)
				 setVehicleHandling(v, "engineAcceleration", 50)
				 setVehicleHandling(v, "engineInertia", 46)
				 setVehicleHandling(v, "engineType", "petrol")
				 setVehicleHandling(v, "brakeDeceleration", 150)
				 setVehicleHandling(v, "steeringLock", 35.0)
				 setVehicleHandling(v, "driveType", "awd")
				 setVehicleHandling(v, "tractionMultiplier", 1)
                 setVehicleHandling(v, "tractionLoss", 0.93)
                 setVehicleHandling(v, "tractionBias", 0.55)
				 setVehicleHandling(v, "dragCoeff",1.4)
				 setVehicleHandling(v, "turnMass", 2400)
				 setVehicleHandling(v, "centerOfMass", { 0.0, 0.0, -0.1})
				 setVehicleHandling(v, "suspensionDamping", 0.3)
				 setVehicleHandling(v, "suspensionForceLevel", 0.6)
				 setVehicleHandling(v, "ABS", false)
			 end	
			 -- Uranus - x
			 if getVehicleModel(v) == 558 then
				setVehicleHandling(v, "mass", 1600)
				setVehicleHandling(v, "turnMass", 3000)
				setVehicleHandling(v, "dragCoeff", 1.8)
				setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
				setVehicleHandling(v, "percentSubmerged", 75)
				setVehicleHandling(v, "tractionMultiplier", 1.28)
				setVehicleHandling(v, "tractionLoss", 0.9)
				setVehicleHandling(v, "tractionBias", 0.497)
				setVehicleHandling(v, "numberOfGears", 5)
				setVehicleHandling(v, "maxVelocity", 209)
				setVehicleHandling(v, "engineAcceleration", 45)
				setVehicleHandling(v, "engineInertia", 40)
				setVehicleHandling(v, "driveType", "rwd")
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 50)
				setVehicleHandling(v, "ABS", false)
				setVehicleHandling(v, "steeringLock", 35)
				setVehicleHandling(v, "monetary", 25000)
				setVehicleHandling(v, "modelFlags", 0x40000001)
				setVehicleHandling(v, "handlingFlags", 0x10308803)
				setVehicleHandling(v, "headLight", 0)
				setVehicleHandling(v, "tailLight", 1)
				setVehicleHandling(v, "animGroup", 0)
				setVehicleHandling(v, "suspensionUpperLimit", 0.20)
				setVehicleHandling(v, "suspensionLowerLimit", -0.08)
			 end	
			 -- Stratum - x
			if getVehicleModel(v) == 561 then
				setVehicleHandling(v, "maxVelocity", 188)
				setVehicleHandling(v, "engineAcceleration", 30.0)
				setVehicleHandling(v, "engineInertia", 50.0)
				setVehicleHandling(v, "tractionMultiplier", 0.75)
                setVehicleHandling(v, "tractionLoss", 0.84)
                setVehicleHandling(v, "tractionBias", 0.55)
			 end	
			 -- Tornado - x
			 if getVehicleModel(v) == 576 then
				setVehicleHandling(v, "maxVelocity", 115)
				setVehicleHandling(v, "engineAcceleration", 17.0)
				setVehicleHandling(v, "engineInertia", 45.0)
				setVehicleHandling(v, "tractionMultiplier", 0.8)
                setVehicleHandling(v, "tractionLoss", 0.8)
                setVehicleHandling(v, "tractionBias", 0.5)
				setVehicleHandling(v, "brakeDeceleration", 50.0)
			 end	
			 
			 if getVehicleModel(v) == 517 then
				setVehicleHandling(v, "maxVelocity", 132)
				setVehicleHandling(v, "suspensionForceLevel", 0.7)
				setVehicleHandling(v, "engineAcceleration", 35.0)
				setVehicleHandling(v, "tractionMultiplier", 1.0)
				setVehicleHandling(v, "engineInertia", 30.0)
				setVehicleHandling(v, "brakeDeceleration", 50.0)
			end
			 
			 -- Voodoo - x
			 if getVehicleModel(v) == 412 then
				setVehicleHandling(v, "maxVelocity", 130)
				setVehicleHandling(v, "engineAcceleration", 16.0)
				setVehicleHandling(v, "engineInertia", 45.0)
			 end	
			 -- Remington - x
			 if getVehicleModel(v) == 534 then
				setVehicleHandling(v, "maxVelocity", 170)
				setVehicleHandling(v, "engineAcceleration", 20.0)
				setVehicleHandling(v, "engineInertia", 50.0)
				setVehicleHandling(v, "tractionMultiplier", 0.75)
                setVehicleHandling(v, "tractionLoss", 0.84)
                setVehicleHandling(v, "tractionBias", 0.55)
			 end
			 -- Blade - x
			 if getVehicleModel(v) == 536 then
				setVehicleHandling(v, "maxVelocity", 152)
				setVehicleHandling(v, "engineAcceleration", 18.0)
				setVehicleHandling(v, "engineInertia", 45.0)
				setVehicleHandling(v, "tractionMultiplier", 0.75)
                setVehicleHandling(v, "tractionLoss", 0.85)
                setVehicleHandling(v, "tractionBias", 0.52)
			 end	
			 -- Savanna - x
			 if getVehicleModel(v) == 567 then
				setVehicleHandling(v, "maxVelocity", 150)
				setVehicleHandling(v, "engineAcceleration", 17.0)
				setVehicleHandling(v, "engineInertia", 47.0)
				setVehicleHandling(v, "tractionMultiplier", 0.76)
                setVehicleHandling(v, "tractionLoss", 0.86)
                setVehicleHandling(v, "tractionBias", 0.6)
			 end	
			 -- Stallion - x
			 if getVehicleModel(v) == 439 then
			setVehicleHandling(v, "maxVelocity", 280)
			setVehicleHandling(v, "engineAcceleration", 67)
			setVehicleHandling(v, "engineInertia", 70.0)
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 420.0)
			setVehicleHandling(v, "ABS", true)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "steeringLock", 35.0)
			setVehicleHandling(v, "tractionMultiplier", 1.05)
			setVehicleHandling(v, "tractionLoss", 0.85)
			setVehicleHandling(v, "tractionBias", 0.49)
			setVehicleHandling(v, "suspensionForceLevel", 1.2)
			setVehicleHandling(v, "centerOfMass", { 0.0, -0.15, -0.3})
			setVehicleHandling(v, "dragCoeff",1.0)
			setVehicleHandling(v, "suspensionHighSpeedDamping", 0.1)
			setVehicleHandling(v, "suspensionLowerLimit", -0.10)
			 end	
			 -- Greenwood - x
			 if getVehicleModel(v) == 410 then
				setVehicleHandling(v, "maxVelocity", 110)
				setVehicleHandling(v, "engineAcceleration", 18.0)
				setVehicleHandling(v, "engineInertia", 50.0)
				setVehicleHandling(v, "tractionMultiplier", 0.74)
                setVehicleHandling(v, "tractionLoss", 0.8)
                setVehicleHandling(v, "tractionBias", 0.51)
			 end	
			  if getVehicleModel(v) == 409 then -- limuzin
				setVehicleHandling(v, "maxVelocity", 176)
				setVehicleHandling(v, "engineAcceleration", 30.0)
				setVehicleHandling(v, "engineInertia", 50.0)
				setVehicleHandling(v, "tractionMultiplier", 0.74)
                setVehicleHandling(v, "tractionLoss", 0.8)
                setVehicleHandling(v, "tractionBias", 0.51)
                setVehicleHandling(v, "suspensionUpperLimit", 0.40)
                setVehicleHandling(v, "suspensionLowerLimit", -0.25)
			 end	
			 -- Banshee - x
			 if getVehicleModel(v) == 429 then
				setVehicleHandling(v, "maxVelocity", 180)
				setVehicleHandling(v, "engineAcceleration", 31.3)
				setVehicleHandling(v, "engineInertia", 40.0)
				setVehicleHandling(v, "tractionMultiplier", 0.83)
                setVehicleHandling(v, "tractionLoss", 0.85)
                setVehicleHandling(v, "tractionBias", 0.47)
				setVehicleHandling(v, "brakeDeceleration", 50.0)
			 end	
			 -- Tampa - x
			 if getVehicleModel(v) == 549 then
				setVehicleHandling(v, "maxVelocity", 160)
				setVehicleHandling(v, "engineAcceleration", 25.0)
				setVehicleHandling(v, "engineInertia", 46.0)
				setVehicleHandling(v, "tractionMultiplier", 0.75)
                setVehicleHandling(v, "tractionLoss", 0.92)
                setVehicleHandling(v, "tractionBias", 0.51)
				setVehicleHandling(v, "brakeDeceleration", 15.0)
				setVehicleHandling(v, "centerOfMass", { 0.0, 0.0, -0.01})
				setVehicleHandling(v, "suspensionDamping", 0.4)
				setVehicleHandling(v, "dragCoeff",2.0)
			 end	
			 -- Jester - x
			 if getVehicleModel(v) == 559 then
				setVehicleHandling(v, "maxVelocity", 222)
				setVehicleHandling(v, "engineAcceleration", 51)
				setVehicleHandling(v, "engineInertia", 40.0)
				setVehicleHandling(v, "tractionMultiplier", 0.83)
                setVehicleHandling(v, "tractionLoss", 0.85)
                setVehicleHandling(v, "tractionBias", 0.47)
				setVehicleHandling(v, "brakeDeceleration", 50.0)
			end 
			 -- Premier - x
			 if getVehicleModel(v) == 426 then
				setVehicleHandling(v, "maxVelocity", 195)
				setVehicleHandling(v, "numberOfGears", 5)
				setVehicleHandling(v, "engineAcceleration", 44.0)
				setVehicleHandling(v, "engineInertia", 45.0)
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "driveType", "rwd")
				setVehicleHandling(v, "steeringLock", 35.0)
				setVehicleHandling(v, "suspensionForceLevel", 1.2)
                setVehicleHandling(v, "suspensionLowerLimit", -0.12)
				setVehicleHandling(v, "centerOfMass", { 0.0, -0.3, -0.1})
			 end	
			 
			 -- taxi
			 if getVehicleModel(v) == 420 then
				setVehicleHandling(v, "maxVelocity", 170)
				setVehicleHandling(v, "engineAcceleration", 25.0)
				setVehicleHandling(v, "engineInertia", 40.0)
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "driveType", "rwd")
				setVehicleHandling(v, "steeringLock", 35.0)
				setVehicleHandling(v, "centerOfMass", { 0.0, 0.0, -0.1})
			 end
			 
			 -- taxi 2
			 if getVehicleModel(v) == 438 then
				setVehicleHandling(v, "maxVelocity", 160)
				setVehicleHandling(v, "engineAcceleration", 20.0)
				setVehicleHandling(v, "engineInertia", 40.0)
				setVehicleHandling(v, "suspensionForceLevel", 0.6)
				setVehicleHandling(v, "driveType", "awd")
			 end
			 
			 -- Bullet - x
			 if getVehicleModel(v) == 541 then
				setVehicleHandling(v, "maxVelocity", 191)
				setVehicleHandling(v, "engineAcceleration", 33.0)
				setVehicleHandling(v, "engineInertia", 50.0)
				setVehicleHandling(v, "steeringLock", 30.0)
				setVehicleHandling(v, "brakeDeceleration", 150.0)
				setVehicleHandling(v, "tractionMultiplier", 0.8)
                setVehicleHandling(v, "tractionLoss", 0.9)
                setVehicleHandling(v, "tractionBias", 0.46)
			 end	
			 -- Slamvan - x
			 if getVehicleModel(v) == 535 then
				setVehicleHandling(v, "maxVelocity", 110)
				setVehicleHandling(v, "engineAcceleration", 17.0)
				setVehicleHandling(v, "engineInertia", 47.0)
				setVehicleHandling(v, "tractionMultiplier", 0.76)
                setVehicleHandling(v, "tractionLoss", 0.86)
                setVehicleHandling(v, "tractionBias", 0.6)
			 end	
			 -- Pony - x
			 if getVehicleModel(v) == 413 then
				setVehicleHandling(v, "maxVelocity", 145)
				setVehicleHandling(v, "engineAcceleration", 17.0)
				setVehicleHandling(v, "engineInertia", 44.0)
				setVehicleHandling(v, "engineType", "diesel")
				setVehicleHandling(v, "brakeDeceleration", 6.0)
				setVehicleHandling(v, "driveType", "rwd")
				setVehicleHandling(v, "steeringLock", 35.0)
				setVehicleHandling(v, "tractionMultiplier", 0.62)
                setVehicleHandling(v, "tractionLoss", 0.9)
                setVehicleHandling(v, "tractionBias", 0.5)
				setVehicleHandling(v, "dragCoeff",2.0)
				setVehicleHandling(v, "suspensionForceLevel", 1.0)
				setVehicleHandling(v, "centerOfMass", { 0.0, 0.4, -0.30})
				setVehicleHandling(v, "suspensionDamping", 0.5)
				setVehicleHandling(v, "suspensionHighSpeedDamping", 2.0)
                setVehicleHandling(v, "suspensionUpperLimit", 0.3)
                setVehicleHandling(v, "suspensionLowerLimit", -0.1)
				setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.3)
				setVehicleHandling(v, "suspensionFrontRearBias", 0.5)
				setVehicleHandling(v, "mass", 2000)
                setVehicleHandling(v, "turnMass", 4500.0)
			 end	
			 -- Police Ranger --> x
			 if getVehicleModel(v) == 599 then
				setVehicleHandling(v, "maxVelocity", 184)
				setVehicleHandling(v, "engineAcceleration", 50.0)
				setVehicleHandling(v, "engineInertia", 75.0)
				setVehicleHandling(v, "suspensionDamping", 50.0)
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 500.0)
				setVehicleHandling(v, "steeringLock", 35.0)
				setVehicleHandling(v, "driveType", "awd")
				setVehicleHandling(v, "tractionMultiplier", 1.0)
                setVehicleHandling(v, "tractionLoss", 0.85)
                setVehicleHandling(v, "tractionBias", 0.47)
				setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
				setVehicleHandling(v, "modelFlags", 0x40000001)
				setVehicleHandling(v, "handlingFlags", 0x10308803)
			end	
             -- FBI Rancher - x
			 if getVehicleModel(v) == 490 then
				setVehicleHandling(v, "maxVelocity", 184)
				setVehicleHandling(v, "engineAcceleration", 50.0)
				setVehicleHandling(v, "engineInertia", 75.0)
				setVehicleHandling(v, "suspensionDamping", 50.0)
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 500.0)
				setVehicleHandling(v, "steeringLock", 35.0)
				setVehicleHandling(v, "driveType", "awd")
				setVehicleHandling(v, "tractionMultiplier", 1.0)
                setVehicleHandling(v, "tractionLoss", 0.85)
                setVehicleHandling(v, "tractionBias", 0.47)
				setVehicleHandling(v, "suspensionForceLevel", 0.7)
				setVehicleHandling(v, "centerOfMass", { 0, -0.12, -0.3 } )
				setVehicleHandling(v, "modelFlags", 0x40000001)
				setVehicleHandling(v, "handlingFlags", 0x10308803)
			 end	
			 -- Police LS -> Ford Crown
			 if getVehicleModel(v) == 596 then
				setVehicleHandling(v, "mass", 1600)
				setVehicleHandling(v, "turnMass", 3000)
				setVehicleHandling(v, "dragCoeff", 1.8)
				setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
				setVehicleHandling(v, "percentSubmerged", 75)
				setVehicleHandling(v, "tractionMultiplier", 0.9)
				setVehicleHandling(v, "tractionLoss", 0.9)
				setVehicleHandling(v, "tractionBias", 0.497)
				setVehicleHandling(v, "numberOfGears", 5)
				setVehicleHandling(v, "maxVelocity", 220)
				setVehicleHandling(v, "engineAcceleration", 60)
				setVehicleHandling(v, "engineInertia", 50)
				setVehicleHandling(v, "driveType", "awd")
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 50)
				setVehicleHandling(v, "ABS", false)
				setVehicleHandling(v, "steeringLock", 35)
				setVehicleHandling(v, "suspensionForceLevel", 0.8)
				setVehicleHandling(v, "suspensionDamping", 0.5)
				setVehicleHandling(v, "suspensionHighSpeedDamping", 0.1)
				setVehicleHandling(v, "suspensionUpperLimit", 0.3)
				setVehicleHandling(v, "suspensionLowerLimit", -0.15)
				setVehicleHandling(v, "suspensionFrontRearBias", 0.55)
				setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.5)
				setVehicleHandling(v, "seatOffsetDistance", 0.2)
				setVehicleHandling(v, "collisionDamageMultiplier", 0.60)
				setVehicleHandling(v, "monetary", 25000)
				setVehicleHandling(v, "modelFlags", 0x40000001)
				setVehicleHandling(v, "handlingFlags", 0x10308803)
				setVehicleHandling(v, "headLight", 0)
				setVehicleHandling(v, "tailLight", 1)
				setVehicleHandling(v, "animGroup", 0)
			end	
			 -- Police LS -> Ford Crown
			 if getVehicleModel(v) == 418 then
				setVehicleHandling(v, "mass", 1600)
				setVehicleHandling(v, "turnMass", 3000)
				setVehicleHandling(v, "dragCoeff", 1.8)
				setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
				setVehicleHandling(v, "percentSubmerged", 75)
				setVehicleHandling(v, "tractionMultiplier", 1.1)
				setVehicleHandling(v, "tractionLoss", 0.9)
				setVehicleHandling(v, "tractionBias", 0.497)
				setVehicleHandling(v, "numberOfGears", 5)
				setVehicleHandling(v, "maxVelocity", 220)
				setVehicleHandling(v, "engineAcceleration", 60)
				setVehicleHandling(v, "engineInertia", 50)
				setVehicleHandling(v, "driveType", "awd")
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 50)
				setVehicleHandling(v, "ABS", false)
				setVehicleHandling(v, "steeringLock", 35)
				setVehicleHandling(v, "suspensionForceLevel", 1.8)
				setVehicleHandling(v, "suspensionDamping", 0.5)
				setVehicleHandling(v, "suspensionHighSpeedDamping", 0.1)
				setVehicleHandling(v, "suspensionUpperLimit", 0.3)
				setVehicleHandling(v, "suspensionLowerLimit", -0.20)
				setVehicleHandling(v, "suspensionFrontRearBias", 0.55)
				setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.5)
				setVehicleHandling(v, "seatOffsetDistance", 0.2)
				setVehicleHandling(v, "collisionDamageMultiplier", 0.60)
				setVehicleHandling(v, "monetary", 25000)
				setVehicleHandling(v, "modelFlags", 0x40000001)
				setVehicleHandling(v, "handlingFlags", 0x10308803)
				setVehicleHandling(v, "headLight", 0)
				setVehicleHandling(v, "tailLight", 1)
				setVehicleHandling(v, "animGroup", 0)
			end	
			 --  SF --> 
		     if getVehicleModel(v) == 597 then
				setVehicleHandling(v, "mass", 1600)
				setVehicleHandling(v, "turnMass", 3000)
				setVehicleHandling(v, "dragCoeff", 1.8)
				setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
				setVehicleHandling(v, "percentSubmerged", 75)
				setVehicleHandling(v, "tractionMultiplier", 0.9)
				setVehicleHandling(v, "tractionLoss", 0.9)
				setVehicleHandling(v, "tractionBias", 0.497)
				setVehicleHandling(v, "numberOfGears", 5)
				setVehicleHandling(v, "maxVelocity", 220)
				setVehicleHandling(v, "engineAcceleration", 60)
				setVehicleHandling(v, "engineInertia", 50)
				setVehicleHandling(v, "driveType", "awd")
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 50)
				setVehicleHandling(v, "ABS", false)
				setVehicleHandling(v, "steeringLock", 35)
				setVehicleHandling(v, "suspensionForceLevel", 0.8)
				setVehicleHandling(v, "suspensionDamping", 0.5)
				setVehicleHandling(v, "suspensionHighSpeedDamping", 0.1)
				setVehicleHandling(v, "suspensionUpperLimit", 0.3)
				setVehicleHandling(v, "suspensionLowerLimit", -0.15)
				setVehicleHandling(v, "suspensionFrontRearBias", 0.55)
				setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.5)
				setVehicleHandling(v, "seatOffsetDistance", 0.2)
				setVehicleHandling(v, "collisionDamageMultiplier", 0.60)
				setVehicleHandling(v, "monetary", 25000)
				setVehicleHandling(v, "modelFlags", 0x40000001)
				setVehicleHandling(v, "handlingFlags", 0x10308803)
				setVehicleHandling(v, "headLight", 0)
				setVehicleHandling(v, "tailLight", 1)
				setVehicleHandling(v, "animGroup", 0)
			end	
			 -- Police LV --> 
			 if getVehicleModel(v) == 598 then
				setVehicleHandling(v, "mass", 1600)
				setVehicleHandling(v, "turnMass", 3000)
				setVehicleHandling(v, "dragCoeff", 1.8)
				setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
				setVehicleHandling(v, "percentSubmerged", 75)
				setVehicleHandling(v, "tractionMultiplier", 0.9)
				setVehicleHandling(v, "tractionLoss", 0.9)
				setVehicleHandling(v, "tractionBias", 0.497)
				setVehicleHandling(v, "numberOfGears", 5)
				setVehicleHandling(v, "maxVelocity", 220)
				setVehicleHandling(v, "engineAcceleration", 60)
				setVehicleHandling(v, "engineInertia", 50)
				setVehicleHandling(v, "driveType", "awd")
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 50)
				setVehicleHandling(v, "ABS", false)
				setVehicleHandling(v, "steeringLock", 35)
				setVehicleHandling(v, "suspensionForceLevel", 0.8)
				setVehicleHandling(v, "suspensionDamping", 0.5)
				setVehicleHandling(v, "suspensionHighSpeedDamping", 0.1)
				setVehicleHandling(v, "suspensionUpperLimit", 0.3)
				setVehicleHandling(v, "suspensionLowerLimit", -0.15)
				setVehicleHandling(v, "suspensionFrontRearBias", 0.55)
				setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.5)
				setVehicleHandling(v, "seatOffsetDistance", 0.2)
				setVehicleHandling(v, "collisionDamageMultiplier", 0.60)
				setVehicleHandling(v, "monetary", 25000)
				setVehicleHandling(v, "modelFlags", 0x40000001)
				setVehicleHandling(v, "handlingFlags", 0x10308803)
				setVehicleHandling(v, "headLight", 0)
				setVehicleHandling(v, "tailLight", 1)
				setVehicleHandling(v, "animGroup", 0)
			end	

			 -- Nebula - x
			 if getVehicleModel(v) == 516 then
				 setVehicleHandling(v, "maxVelocity", 196)
				 setVehicleHandling(v, "engineAcceleration", 50)
				 setVehicleHandling(v, "engineInertia", 46)
				 setVehicleHandling(v, "engineType", "petrol")
				 setVehicleHandling(v, "brakeDeceleration", 150)
				 setVehicleHandling(v, "steeringLock", 35.0)
				 setVehicleHandling(v, "driveType", "awd")
				 setVehicleHandling(v, "tractionMultiplier", 1)
                 setVehicleHandling(v, "tractionLoss", 0.93)
                 setVehicleHandling(v, "tractionBias", 0.55)
				 setVehicleHandling(v, "dragCoeff",1.4)
				 setVehicleHandling(v, "turnMass", 2400)
				 setVehicleHandling(v, "centerOfMass", { 0.0, 0.5, 0.0})
				 setVehicleHandling(v, "suspensionDamping", 0.3)
				 setVehicleHandling(v, "suspensionForceLevel", 1.3)
				 setVehicleHandling(v, "ABS", false)
			end	
			
			 -- egyedi fos - x
			 if getVehicleModel(v) == 436 then
				setVehicleHandling(v, "mass", 1600)
				setVehicleHandling(v, "turnMass", 3000)
				setVehicleHandling(v, "dragCoeff", 1.8)
				setVehicleHandling(v, "centerOfMass", { 0, 0.10, -0.3 } )
				setVehicleHandling(v, "percentSubmerged", 75)
				setVehicleHandling(v, "tractionMultiplier", 0.9)
				setVehicleHandling(v, "tractionLoss", 0.9)
				setVehicleHandling(v, "tractionBias", 0.497)
				setVehicleHandling(v, "numberOfGears", 5)
				setVehicleHandling(v, "maxVelocity", 197)
				setVehicleHandling(v, "engineAcceleration", 60)
				setVehicleHandling(v, "engineInertia", 40)
				setVehicleHandling(v, "driveType", "awd")
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 50)
				setVehicleHandling(v, "ABS", true)
				setVehicleHandling(v, "steeringLock", 35)
				setVehicleHandling(v, "monetary", 25000)
				setVehicleHandling(v, "modelFlags", 0x40000001)
				setVehicleHandling(v, "handlingFlags", 0x10308803)
				setVehicleHandling(v, "headLight", 0)
				setVehicleHandling(v, "tailLight", 1)
				setVehicleHandling(v, "animGroup", 0)
				setVehicleHandling(v, "suspensionUpperLimit", 0.20)
				setVehicleHandling(v, "suspensionLowerLimit", -0.12)
				 
			end	 
		 	 -- Flash - x
			 if getVehicleModel(v) == 565 then
				 setVehicleHandling(v, "maxVelocity", 190)
				 setVehicleHandling(v, "engineAcceleration", 25.0)
				 setVehicleHandling(v, "engineInertia", 47.0)
				 setVehicleHandling(v, "engineType", "petrol")
				 setVehicleHandling(v, "brakeDeceleration", 150.0)
				 setVehicleHandling(v, "steeringLock", 35.0)
				 setVehicleHandling(v, "driveType", "fwd")
				 setVehicleHandling(v, "tractionMultiplier", 0.8)
                 setVehicleHandling(v, "tractionLoss", 0.93)
                 setVehicleHandling(v, "tractionBias", 0.55)
				 setVehicleHandling(v, "dragCoeff",1.4)
				 setVehicleHandling(v, "turnMass", 2400)
				 setVehicleHandling(v, "centerOfMass", { 0.0, 0.0, -0.1})
				 setVehicleHandling(v, "suspensionDamping", 0.4)
		    end 
			 -- Fortune - x
			 if getVehicleModel(v) == 526 then
				setVehicleHandling(v, "maxVelocity", 130)
				setVehicleHandling(v, "engineAcceleration", 24.0)
				setVehicleHandling(v, "engineInertia", 50.0)
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 6.0)
				setVehicleHandling(v, "ABS", true)
				setVehicleHandling(v, "steeringLock", 35.0)
				setVehicleHandling(v, "driveType", "fwd")
				setVehicleHandling(v, "tractionMultiplier", 0.74)
                setVehicleHandling(v, "tractionLoss", 0.83)
                setVehicleHandling(v, "tractionBias", 0.51)
				setVehicleHandling(v, "mass", 1300)
                setVehicleHandling(v, "turnMass", 2500)
				setVehicleHandling(v, "dragCoeff",1.5)
			end	
              -- Intruder - x
			 if getVehicleModel(v) == 546 then
				setVehicleHandling(v, "maxVelocity", 110)
				setVehicleHandling(v, "engineAcceleration", 17.0)
				setVehicleHandling(v, "engineInertia", 40.0)
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 10.0)
				setVehicleHandling(v, "steeringLock", 35.0)
				setVehicleHandling(v, "driveType", "rwd")
				setVehicleHandling(v, "tractionMultiplier", 0.9)
                setVehicleHandling(v, "tractionLoss", 0.8)
                setVehicleHandling(v, "tractionBias", 0.55)
				setVehicleHandling(v, "mass", 1400)
                setVehicleHandling(v, "turnMass", 3000)
				setVehicleHandling(v, "centerOfMass", { 0.0, -0.01, -0.1})
				setVehicleHandling(v, "suspensionForceLevel", 1.5)
				setVehicleHandling(v, "suspensionDamping", 0.4)
				setVehicleHandling(v, "suspensionUpperLimit", 0.30)
                setVehicleHandling(v, "suspensionLowerLimit", -0.13)
				setVehicleHandling(v, "suspensionFrontRearBias", 0.7)
			 end	
			 
			 if getVehicleModel(v) == 578 then
				setVehicleHandling(v, "maxVelocity", 120)
			end
			 -- Clover - x
			 if getVehicleModel(v) == 542 then
				setVehicleHandling(v, "maxVelocity", 126)
				setVehicleHandling(v, "engineAcceleration", 19.0)
				setVehicleHandling(v, "engineInertia", 50.0)
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 500.0)
				setVehicleHandling(v, "steeringLock", 35.0)
				setVehicleHandling(v, "driveType", "rwd")
				setVehicleHandling(v, "numberOfGears", 3)
				setVehicleHandling(v, "tractionMultiplier", 0.65)
                setVehicleHandling(v, "tractionLoss", 0.8)
                setVehicleHandling(v, "tractionBias", 0.52)
			 end	
			 -- Tahoma - x
			 if getVehicleModel(v) == 566 then
				setVehicleHandling(v, "maxVelocity", 150)
				setVehicleHandling(v, "engineAcceleration", 24.0)
				setVehicleHandling(v, "engineInertia", 50.0)
				setVehicleHandling(v, "steeringLock", 30.0)
				setVehicleHandling(v, "brakeDeceleration", 150.0)
				setVehicleHandling(v, "tractionMultiplier", 0.8)
                setVehicleHandling(v, "tractionLoss", 0.75)
                setVehicleHandling(v, "tractionBias", 0.46)
			 end	
			 -- Elegy - x
			 if getVehicleModel(v) == 562 then
				setVehicleHandling(v, "mass", 1500)
				setVehicleHandling(v, "turnMass", 3000)
				setVehicleHandling(v, "dragCoeff", 1.4)
				setVehicleHandling(v, "centerOfMass", { 0, 0.2, -0.15 } )
				setVehicleHandling(v, "percentSubmerged", 75)
				setVehicleHandling(v, "tractionMultiplier", 0.86)
				setVehicleHandling(v, "tractionLoss", 0.9)
				setVehicleHandling(v, "tractionBias", 0.455)
				setVehicleHandling(v, "numberOfGears", 5)
				setVehicleHandling(v, "maxVelocity", 210)
				setVehicleHandling(v, "engineAcceleration", 39)
				setVehicleHandling(v, "engineInertia", 40)
				setVehicleHandling(v, "driveType", "rwd")
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 50)
				setVehicleHandling(v, "steeringLock", 35)
				setVehicleHandling(v, "suspensionForceLevel", 1)
				setVehicleHandling(v, "suspensionDamping", 0.2)
				setVehicleHandling(v, "suspensionHighSpeedDamping", 0)
				setVehicleHandling(v, "suspensionUpperLimit", 0.28)
				setVehicleHandling(v, "suspensionLowerLimit", -0.1)
				setVehicleHandling(v, "suspensionFrontRearBias", 0.5)
				setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.3)
				setVehicleHandling(v, "seatOffsetDistance", 0.25)
				setVehicleHandling(v, "collisionDamageMultiplier", 0.6)
				setVehicleHandling(v, "modelFlags", 0x40002040)
				setVehicleHandling(v, "handlingFlags", 0x10000002)
			 end	
			 -- Blista Compact - x
			 if getVehicleModel(v) == 496 then
				setVehicleHandling(v, "maxVelocity", 135)
				setVehicleHandling(v, "engineAcceleration", 20.0)
				setVehicleHandling(v, "engineInertia", 48.0)
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 9.0)
				setVehicleHandling(v, "steeringLock", 35.0)
				setVehicleHandling(v, "driveType", "fwd")
				setVehicleHandling(v, "tractionMultiplier", 0.92)
                setVehicleHandling(v, "tractionLoss", 0.95)
                setVehicleHandling(v, "tractionBias", 0.47)
				setVehicleHandling(v, "centerOfMass", { 0.0, -0.1, -0.1})
				setVehicleHandling(v, "suspensionForceLevel", 1.5)
				setVehicleHandling(v, "suspensionDamping", 0.2)
				setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.5)
				setVehicleHandling(v, "mass", 1700) 
				setVehicleHandling(v, "turnmass", 3500) 
			 end	
			 -- Willard - x
			 if getVehicleModel(v) == 529 then
				setVehicleHandling(v, "maxVelocity", 152)
				setVehicleHandling(v, "engineAcceleration", 25.0)
				setVehicleHandling(v, "engineInertia", 50.0)
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 25.0)
				setVehicleHandling(v, "steeringLock", 35.0)
				setVehicleHandling(v, "driveType", "awd")
				setVehicleHandling(v, "tractionMultiplier", 0.86)
                setVehicleHandling(v, "tractionLoss", 0.86)
                setVehicleHandling(v, "tractionBias", 0.51)
				setVehicleHandling(v, "mass", 1350)
                setVehicleHandling(v, "turnMass", 3000.0)
				setVehicleHandling(v, "centerOfMass", { 0.0, -0.15, -0.15})
				setVehicleHandling(v, "suspensionForceLevel", 1.8)
                setVehicleHandling(v, "suspensionDamping", 0.2)
                setVehicleHandling(v, "suspensionHighSpeedDamping", 1.0)
			 end	
			 -- Club - x
			 if getVehicleModel(v) == 589 then
				setVehicleHandling(v, "mass", 1700.0)
				setVehicleHandling(v, "turnMass", 3300.0)
				setVehicleHandling(v, "dragCoeff", 1.4)
				setVehicleHandling(v, "centerOfMass", { 0.0, -0.03, -0.1 } )
				setVehicleHandling(v, "percentSubmerged", 80)
				setVehicleHandling(v, "tractionMultiplier", 0.78)
				setVehicleHandling(v, "tractionLoss", 0.74)
				setVehicleHandling(v, "tractionBias", 0.46)
				setVehicleHandling(v, "numberOfGears", 4)
				setVehicleHandling(v, "maxVelocity", 115.0)
				setVehicleHandling(v, "engineAcceleration", 10.0)
				setVehicleHandling(v, "engineInertia", 5.0)
				setVehicleHandling(v, "driveType", "fwd")
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 50.0)
				setVehicleHandling(v, "steeringLock", 35.0)
				setVehicleHandling(v, "suspensionForceLevel", 0.8)
				setVehicleHandling(v, "suspensionDamping", 0.3)
				setVehicleHandling(v, "suspensionHighSpeedDamping", 0.0)
				setVehicleHandling(v, "suspensionUpperLimit", 0.36)
				setVehicleHandling(v, "suspensionLowerLimit", -0.2)
				setVehicleHandling(v, "suspensionFrontRearBias", 0.51)
				setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.3)
				setVehicleHandling(v, "seatOffsetDistance", 0.44)
				setVehicleHandling(v, "collisionDamageMultiplier", 0.32)
				setVehicleHandling(v, "modelFlags", 0x2000)
				setVehicleHandling(v, "handlingFlags", 0x4300002)
				setVehicleHandling(v, "headLight", 0)
				setVehicleHandling(v, "tailLight", 1)
				setVehicleHandling(v, "animGroup", 0)
			 end	
			 -- Primo - x
			 if getVehicleModel(v) == 547 then
				setVehicleHandling(v, "maxVelocity", 160)
				setVehicleHandling(v, "engineAcceleration", 23.0)
				setVehicleHandling(v, "engineInertia", 50.0)
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 300.0)
				setVehicleHandling(v, "steeringLock", 35.0)
				setVehicleHandling(v, "driveType", "fwd")
				setVehicleHandling(v, "tractionMultiplier", 0.74)
                setVehicleHandling(v, "tractionLoss", 0.86)
                setVehicleHandling(v, "tractionBias", 0.53)
			 end	 
			 -- Yosemite - x
			 if getVehicleModel(v) == 554 then
				setVehicleHandling(v, "maxVelocity", 157)
				setVehicleHandling(v, "engineAcceleration", 25.0)
				setVehicleHandling(v, "engineInertia", 50.0)
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 10.0)
				setVehicleHandling(v, "ABS", true)
				setVehicleHandling(v, "driveType", "awd")
				setVehicleHandling(v, "steeringLock", 35.0)
				setVehicleHandling(v, "tractionMultiplier", 0.83)
                setVehicleHandling(v, "tractionLoss", 0.8)
                setVehicleHandling(v, "tractionBias", 0.47)
				setVehicleHandling(v, "mass", 3000)
                setVehicleHandling(v, "turnMass", 5000)
				setVehicleHandling(v, "centerOfMass", { 0.0, 0.0, -0.1})
				setVehicleHandling(v, "dragCoeff",1.8)
			 end	
			 -- Sultan - x
			 if getVehicleModel(v) == 560 then
				setVehicleHandling(v, "maxVelocity", 216)
				setVehicleHandling(v, "engineAcceleration", 50)
				setVehicleHandling(v, "engineInertia", 51.0)
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 150.0)
				setVehicleHandling(v, "ABS", true)
				setVehicleHandling(v, "steeringLock", 35.0)
				setVehicleHandling(v, "driveType", "awd")
				setVehicleHandling(v, "tractionMultiplier", 1.50)
                setVehicleHandling(v, "tractionLoss", 0.65)
                setVehicleHandling(v, "tractionBias", 0.51)
				setVehicleHandling(v, "suspensionForceLevel", 1)
				setVehicleHandling(v, "suspensionDamping", 0.7)
				setVehicleHandling(v, "centerOfMass", { 0.0, 0.1, -0.25})
				setVehicleHandling(v, "dragCoeff",1.0)
				setVehicleHandling(v, "mass", 1500)
                setVehicleHandling(v, "turnMass", 2000.0)
				setVehicleHandling(v, "modelFlags", 0x800)
				setVehicleHandling(v, "handlingFlags", 0x4004402)
			 end	
			 -- Huntley - x
			 if getVehicleModel(v) == 579 then
				setVehicleHandling(v, "maxVelocity", 174)
				setVehicleHandling(v, "engineAcceleration", 27.5)
				setVehicleHandling(v, "engineInertia", 50.0)
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "dragCoeff",2.0)
				setVehicleHandling(v, "brakeDeceleration", 500.0)
				setVehicleHandling(v, "ABS", true)
				setVehicleHandling(v, "steeringLock", 35.0)
				setVehicleHandling(v, "driveType", "awd")
				setVehicleHandling(v, "tractionMultiplier", 0.9)
                setVehicleHandling(v, "tractionLoss", 0.8)
                setVehicleHandling(v, "tractionBias", 0.5)
				setVehicleHandling(v, "suspensionDamping", 0.75)
			 end	
			 -- Broadway - x
			 if getVehicleModel(v) == 575 then
				setVehicleHandling(v, "maxVelocity", 114)
				setVehicleHandling(v, "suspensionUpperLimit", 0.15)
				setVehicleHandling(v, "suspensionLowerLimit", -0.1)

			 end	
			 -- Cadrona - x
			 if getVehicleModel(v) == 527 then
				setVehicleHandling(v, "maxVelocity", 156)
				setVehicleHandling(v, "engineAcceleration", 27.0)
				setVehicleHandling(v, "engineInertia", 45.0)
				setVehicleHandling(v, "turnMass", 3000.0)
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 50.0)
				setVehicleHandling(v, "ABS", true)
				setVehicleHandling(v, "driveType", "rwd")
				setVehicleHandling(v, "steeringLock", 35.0)
				setVehicleHandling(v, "tractionMultiplier", 0.97)
                setVehicleHandling(v, "tractionLoss", 0.77)
                setVehicleHandling(v, "tractionBias", 0.5)
				setVehicleHandling(v, "centerOfMass", { 0.0, 0.15, -0.25})
				setVehicleHandling(v, "suspensionForceLevel", 1.6)
			 end	
			 -- Admiral - x
			 if getVehicleModel(v) == 445 then
				setVehicleHandling(v, "mass", 1200)
				setVehicleHandling(v, "turnMass", 2000)
				setVehicleHandling(v, "dragCoeff", 1.5)
				setVehicleHandling(v, "centerOfMass", { 0, 0, -0.05 } )
				setVehicleHandling(v, "percentSubmerged", 75)
				setVehicleHandling(v, "tractionMultiplier", 1.2)
				setVehicleHandling(v, "tractionLoss", 0.75)
				setVehicleHandling(v, "tractionBias", 0.49)
				setVehicleHandling(v, "numberOfGears", 5)
				setVehicleHandling(v, "maxVelocity", 187)
				setVehicleHandling(v, "engineAcceleration", 35)
				setVehicleHandling(v, "engineInertia", 40)
				setVehicleHandling(v, "driveType", "awd")
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 50)
				setVehicleHandling(v, "ABS", true)
				setVehicleHandling(v, "steeringLock", 35)
				setVehicleHandling(v, "suspensionForceLevel", 1.4)
				setVehicleHandling(v, "suspensionDamping", 0.5)
				setVehicleHandling(v, "suspensionHighSpeedDamping", 0.1)
				setVehicleHandling(v, "suspensionUpperLimit", 0.25)
				setVehicleHandling(v, "suspensionLowerLimit", -0.15)
				setVehicleHandling(v, "suspensionFrontRearBias", 0.5)
				setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0)
				setVehicleHandling(v, "seatOffsetDistance", 0.2)
				setVehicleHandling(v, "collisionDamageMultiplier", 0.56)
				setVehicleHandling(v, "modelFlags", 0x40040040)
				setVehicleHandling(v, "handlingFlags", 0x404402)
			 end	
			 -- Stafford - x
			 if getVehicleModel(v) == 580 then
				setVehicleHandling(v, "maxVelocity", 167)
				setVehicleHandling(v, "engineAcceleration", 52.5)
				setVehicleHandling(v, "engineInertia", 45.0)
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 370.0)
				setVehicleHandling(v, "ABS", true)
				setVehicleHandling(v, "driveType", "awd")
				setVehicleHandling(v, "steeringLock", 35.0)
				setVehicleHandling(v, "tractionMultiplier", 1.3)
                setVehicleHandling(v, "tractionLoss", 0.65)
                setVehicleHandling(v, "tractionBias", 0.49)
				setVehicleHandling(v, "suspensionForceLevel", 1.0)
				setVehicleHandling(v, "suspensionDamping", 1.0)
				setVehicleHandling(v, "suspensionUpperLimit", 0.3)
                setVehicleHandling(v, "suspensionLowerLimit", -0.15)
				setVehicleHandling(v, "centerOfMass", { 0.0, -0.15, 0.0})
				setVehicleHandling(v, "mass", 1600)
                setVehicleHandling(v, "turnMass", 3500.0)
			  end	
			  -- Emperor - x
			  if getVehicleModel(v) == 585 then
				setVehicleHandling(v, "maxVelocity", 155)
				setVehicleHandling(v, "engineAcceleration", 26.5)
				setVehicleHandling(v, "engineInertia", 50.0)
				setVehicleHandling(v, "turnMass", 3500.0)
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 50.0)
				setVehicleHandling(v, "ABS", true)
				setVehicleHandling(v, "driveType", "awd")
				setVehicleHandling(v, "steeringLock", 35.0)
				setVehicleHandling(v, "tractionMultiplier", 1.1)
                setVehicleHandling(v, "tractionLoss", 0.8)
                setVehicleHandling(v, "tractionBias", 0.5)
				setVehicleHandling(v, "suspensionDamping", 0.9)
				setVehicleHandling(v, "centerOfMass", { 0.0, 0.0, -0.15})
				setVehicleHandling(v, "turnMass", 3000.0)
			 end	
			 -- Regina - x
			 if getVehicleModel(v) == 479 then
				setVehicleHandling(v, "maxVelocity", 142)
				setVehicleHandling(v, "engineAcceleration", 16.3)
				setVehicleHandling(v, "engineInertia", 47.0)
				setVehicleHandling(v, "turnMass", 2500.0)
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 420.0)
				setVehicleHandling(v, "ABS", true)
				setVehicleHandling(v, "driveType", "awd")
				setVehicleHandling(v, "steeringLock", 35.0)
				setVehicleHandling(v, "tractionMultiplier", 1.03)
                setVehicleHandling(v, "tractionLoss", 0.80)
                setVehicleHandling(v, "tractionBias", 0.51)
				setVehicleHandling(v, "suspensionDamping", 0.9)
				setVehicleHandling(v, "centerOfMass", { 0.0, 0.0, -0.10})
				setVehicleHandling(v, "mass", 1600.0)
				setVehicleHandling(v, "dragCoeff", 1.7)
				setVehicleHandling(v, "percentSubmerged", 75)
				setVehicleHandling(v, "numberOfGears", 5)
				setVehicleHandling(v, "suspensionForceLevel", 1.2)
				setVehicleHandling(v, "suspensionHighSpeedDamping", 0.0)
				setVehicleHandling(v, "suspensionUpperLimit", 0.32)
				setVehicleHandling(v, "suspensionLowerLimit", -0.12)
				setVehicleHandling(v, "suspensionFrontRearBias", 0.55)
				setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.3)
				setVehicleHandling(v, "seatOffsetDistance", 0.2)
				setVehicleHandling(v, "collisionDamageMultiplier", 0.56)
				setVehicleHandling(v, "modelFlags", 0x0)
				setVehicleHandling(v, "handlingFlags", 0x400000)
			 end	
			 -- alpha - 
			 if getVehicleModel(v) == 602 then
			setVehicleHandling(v, "maxVelocity", 230)
			setVehicleHandling(v, "engineAcceleration", 67)
			setVehicleHandling(v, "engineInertia", 45.0)
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 420.0)
			setVehicleHandling(v, "ABS", true)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "steeringLock", 35.0)
			setVehicleHandling(v, "tractionMultiplier", 1.05)
			setVehicleHandling(v, "tractionLoss", 0.85)
			setVehicleHandling(v, "tractionBias", 0.49)
			setVehicleHandling(v, "suspensionForceLevel", 1.1)
			setVehicleHandling(v, "centerOfMass", { 0.0, -0.15, -0.3})
			setVehicleHandling(v, "dragCoeff",1.0)
			setVehicleHandling(v, "suspensionHighSpeedDamping", 0.1)
			setVehicleHandling(v, "suspensionLowerLimit", -0.10)
			 end	
			 -- Bravura
			 if getVehicleModel(v) == 401 then
				setVehicleHandling(v, "mass", 1400) 
				setVehicleHandling(v, "turnMass", 3000)
				setVehicleHandling(v, "dragCoeff", 1.1)
				setVehicleHandling(v, "centerOfMass", { 0, -0.15, -0.3 } )
				setVehicleHandling(v, "percentSubmerged", 70)
				setVehicleHandling(v, "tractionMultiplier", 1)
				setVehicleHandling(v, "tractionLoss", 0.83)
				setVehicleHandling(v, "tractionBias", 0.48)
				setVehicleHandling(v, "numberOfGears", 5)
				setVehicleHandling(v, "maxVelocity", 140)
				setVehicleHandling(v, "engineAcceleration", 19)
				setVehicleHandling(v, "engineInertia", 50)
				setVehicleHandling(v, "driveType", "rwd")
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 50)
				setVehicleHandling(v, "ABS", true)
				setVehicleHandling(v, "steeringLock", 35)
				setVehicleHandling(v, "suspensionForceLevel", 1)
				setVehicleHandling(v, "suspensionDamping", 0.3)
				setVehicleHandling(v, "suspensionHighSpeedDamping", 0.1)
				setVehicleHandling(v, "suspensionUpperLimit", 0.31)
				setVehicleHandling(v, "suspensionLowerLimit", -0.15)
				setVehicleHandling(v, "suspensionFrontRearBias", 0.57)
				setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0)
				setVehicleHandling(v, "seatOffsetDistance", 0.26)
				setVehicleHandling(v, "collisionDamageMultiplier", 0.5)
				setVehicleHandling(v, "modelFlags", 0x40000040)
				setVehicleHandling(v, "handlingFlags", 0x104402)
			 end	
			 -- Sunrise - x
			 if getVehicleModel(v) == 550 then
				setVehicleHandling(v, "maxVelocity", 145)
				setVehicleHandling(v, "engineAcceleration", 17.0)
				setVehicleHandling(v, "engineInertia", 50.0)
				setVehicleHandling(v, "turnMass", 3500.0)
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 420.0)
				setVehicleHandling(v, "ABS", true)
				setVehicleHandling(v, "driveType", "rwd")
				setVehicleHandling(v, "steeringLock", 35.0)
				setVehicleHandling(v, "tractionMultiplier", 1.03)
                setVehicleHandling(v, "tractionLoss", 0.75)
                setVehicleHandling(v, "tractionBias", 0.5)
				setVehicleHandling(v, "suspensionDamping", 0.9)
				setVehicleHandling(v, "centerOfMass", { 0.0, 0.0, -0.15})
				setVehicleHandling(v, "modelFlags", 0x40002000)
			 end	
			 -- Sentinel - x
			 if getVehicleModel(v) == 405 then
				setVehicleHandling(v, "mass", 1200)
				setVehicleHandling(v, "turnMass", 2000)
				setVehicleHandling(v, "dragCoeff", 1.5)
				setVehicleHandling(v, "centerOfMass", { 0, 0, -0.05 } )
				setVehicleHandling(v, "percentSubmerged", 75)
				setVehicleHandling(v, "tractionMultiplier", 1)
				setVehicleHandling(v, "tractionLoss", 0.75)
				setVehicleHandling(v, "tractionBias", 0.49)
				setVehicleHandling(v, "numberOfGears", 5)
				setVehicleHandling(v, "maxVelocity", 167)
				setVehicleHandling(v, "engineAcceleration", 33)
				setVehicleHandling(v, "engineInertia", 40)
				setVehicleHandling(v, "driveType", "awd")
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 50)
				setVehicleHandling(v, "ABS", true)
				setVehicleHandling(v, "steeringLock", 35)
				setVehicleHandling(v, "suspensionForceLevel", 1.4)
				setVehicleHandling(v, "suspensionDamping", 0.5)
				setVehicleHandling(v, "suspensionHighSpeedDamping", 0.1)
				setVehicleHandling(v, "suspensionUpperLimit", 0.25)
				setVehicleHandling(v, "suspensionLowerLimit", -0.15)
				setVehicleHandling(v, "suspensionFrontRearBias", 0.5)
				setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0)
				setVehicleHandling(v, "seatOffsetDistance", 0.2)
				setVehicleHandling(v, "collisionDamageMultiplier", 0.56)
				setVehicleHandling(v, "modelFlags", 0x40040040)
				setVehicleHandling(v, "handlingFlags", 0x404402)
			 end	
			 -- Phoenix - x
			 if getVehicleModel(v) == 603 then
				setVehicleHandling(v, "maxVelocity", 174)
				setVehicleHandling(v, "engineAcceleration", 28.0)
				setVehicleHandling(v, "engineInertia", 50.0)
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 20.0)
				setVehicleHandling(v, "driveType", "rwd")
				setVehicleHandling(v, "steeringLock", 35.0)
				setVehicleHandling(v, "tractionMultiplier", 0.96)
                setVehicleHandling(v, "tractionLoss", 0.79)
                setVehicleHandling(v, "tractionBias", 0.5)
				setVehicleHandling(v, "centerOfMass", { 0.0, -0.15, 0.0})
				setVehicleHandling(v, "suspensionDamping", 0.1)
				setVehicleHandling(v, "suspensionForceLevel", 1)
				setVehicleHandling(v, "suspensionUpperLimit", 0.05)
				setVehicleHandling(v, "suspensionLowerLimit", -0.10)
				setVehicleHandling(v, "mass", 1500)
                setVehicleHandling(v, "turnMass", 4000.0)
			 end	
			 -- Merit - x
			 if getVehicleModel(v) == 551 then
				setVehicleHandling(v, "maxVelocity", 158)
				setVehicleHandling(v, "engineAcceleration", 40.0)
				setVehicleHandling(v, "engineInertia", 53.0)
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 6.0)
				setVehicleHandling(v, "ABS", true)
				setVehicleHandling(v, "driveType", "rwd")
				setVehicleHandling(v, "steeringLock", 35.0)
				setVehicleHandling(v, "tractionMultiplier", 0.9)
                setVehicleHandling(v, "tractionLoss", 0.67)
                setVehicleHandling(v, "tractionBias", 0.48)
				setVehicleHandling(v, "suspensionForceLevel", 1)
				setVehicleHandling(v, "suspensionUpperLimit", 0.05)
				setVehicleHandling(v, "suspensionLowerLimit", -0.15)
				setVehicleHandling(v, "centerOfMass", { 0.0, 0.2, -0.08})
			 end	
			 -- Washington - x
			 if getVehicleModel(v) == 421 then
				setVehicleHandling(v, "maxVelocity", 150)
				setVehicleHandling(v, "engineAcceleration", 20.0)
				setVehicleHandling(v, "engineInertia", 40.0)
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 480.0)
				setVehicleHandling(v, "ABS", true)
				setVehicleHandling(v, "driveType", "rwd")
				setVehicleHandling(v, "steeringLock", 35.0)
				setVehicleHandling(v, "tractionMultiplier", 0.96)
                setVehicleHandling(v, "tractionLoss", 0.87)
                setVehicleHandling(v, "tractionBias", 0.5)
			 end	
			 -- Euros - x
			 if getVehicleModel(v) == 587 then
				setVehicleHandling(v, "mass", 1400)
				setVehicleHandling(v, "turnMass", 2600)
				setVehicleHandling(v, "dragCoeff", 1)
				setVehicleHandling(v, "centerOfMass", { 0, 0.1, -0.1 } )
				setVehicleHandling(v, "percentSubmerged", 75)
				setVehicleHandling(v, "tractionMultiplier", 1.05)
				setVehicleHandling(v, "tractionLoss", 0.85)
				setVehicleHandling(v, "tractionBias", 0.533)
				setVehicleHandling(v, "numberOfGears", 5)
				setVehicleHandling(v, "maxVelocity", 185)
				setVehicleHandling(v, "engineAcceleration", 31)
				setVehicleHandling(v, "engineInertia", 40)
				setVehicleHandling(v, "driveType", "awd")
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 50)
				setVehicleHandling(v, "ABS", true)
				setVehicleHandling(v, "steeringLock", 35)
				setVehicleHandling(v, "suspensionForceLevel", 1.2)
				setVehicleHandling(v, "suspensionDamping", 0.2)
				setVehicleHandling(v, "suspensionHighSpeedDamping", 0)
				setVehicleHandling(v, "suspensionUpperLimit", 0.3)
				setVehicleHandling(v, "suspensionLowerLimit", -0.1)
				setVehicleHandling(v, "suspensionFrontRearBias", 0.5)
				setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.3)
				setVehicleHandling(v, "seatOffsetDistance", 0.25)
				setVehicleHandling(v, "collisionDamageMultiplier", 0.6)
				setVehicleHandling(v, "monetary", 35000)
				setVehicleHandling(v, "modelFlags", 0x40002804)
				setVehicleHandling(v, "handlingFlags", 0x300002)
				setVehicleHandling(v, "headLight", 1)
				setVehicleHandling(v, "tailLight", 1)
				setVehicleHandling(v, "animGroup", 0)
			 end	
             -- Turismo - x
			 if getVehicleModel(v) == 451 then
				setVehicleHandling(v, "maxVelocity", 228)
				setVehicleHandling(v, "engineAcceleration", 60.5)
				setVehicleHandling(v, "engineInertia", 46.0)
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 390.0)
				setVehicleHandling(v, "ABS", true)
				setVehicleHandling(v, "driveType", "awd")
				setVehicleHandling(v, "steeringLock", 35.0)
				setVehicleHandling(v, "tractionMultiplier", 1.51)
                setVehicleHandling(v, "tractionLoss", 0.93)
                setVehicleHandling(v, "tractionBias", 0.36)
				setVehicleHandling(v, "centerOfMass", { 0.0, -0.3, -0.3})
				setVehicleHandling(v, "suspensionDamping", 0.2)
				setVehicleHandling(v, "suspensionForceLevel", 0.75)
				setVehicleHandling(v, "mass", 1550)
			 end
             -- Virgo - x
			 if getVehicleModel(v) == 491 then
				setVehicleHandling(v, "maxVelocity", 228)
				setVehicleHandling(v, "engineAcceleration", 60.5)
				setVehicleHandling(v, "engineInertia", 46.0)
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 390.0)
				setVehicleHandling(v, "ABS", true)
				setVehicleHandling(v, "driveType", "awd")
				setVehicleHandling(v, "steeringLock", 35.0)
				setVehicleHandling(v, "tractionMultiplier", 1.51)
                setVehicleHandling(v, "tractionLoss", 0.93)
                setVehicleHandling(v, "tractionBias", 0.36)
				setVehicleHandling(v, "centerOfMass", { 0.0, 0.0, -0.3})
				setVehicleHandling(v, "suspensionDamping", 0.2)
				setVehicleHandling(v, "suspensionForceLevel", 0.75)
				setVehicleHandling(v, "mass", 1550)
			 end	
			 -- Infernus - x
			 if getVehicleModel(v) == 411 then
				setVehicleHandling(v, "maxVelocity", 231)
				setVehicleHandling(v, "engineAcceleration", 70)
				setVehicleHandling(v, "engineInertia", 50.0)
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 420.0)
				setVehicleHandling(v, "ABS", true)
				setVehicleHandling(v, "driveType", "awd")
				setVehicleHandling(v, "steeringLock", 35.0)
				setVehicleHandling(v, "tractionMultiplier", 1.05)
                setVehicleHandling(v, "tractionLoss", 0.85)
                setVehicleHandling(v, "tractionBias", 0.49)
				setVehicleHandling(v, "suspensionForceLevel", 1.2)
				setVehicleHandling(v, "centerOfMass", { 0.0, -0.15, -0.3})
				setVehicleHandling(v, "dragCoeff",1.0)
				setVehicleHandling(v, "suspensionHighSpeedDamping", 0.1)
			 end	
             -- Buffalo - x
			 if getVehicleModel(v) == 402 then
				setVehicleHandling(v, "maxVelocity", 180)
				setVehicleHandling(v, "engineAcceleration", 52)
				setVehicleHandling(v, "engineInertia", 47.0)
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 100.0)
				setVehicleHandling(v, "driveType", "awd")
				setVehicleHandling(v, "steeringLock", 35.0)
				setVehicleHandling(v, "tractionMultiplier", 1.03)
                setVehicleHandling(v, "tractionLoss", 0.75)
                setVehicleHandling(v, "tractionBias", 0.49)
				setVehicleHandling(v, "suspensionForceLevel", 1)
				setVehicleHandling(v, "centerOfMass", { 0.0, 0.1, -0.15})
				setVehicleHandling(v, "suspensionDamping", 0.3)
			 end	
             -- cheetah - x
			 if getVehicleModel(v) == 415 then
				setVehicleHandling(v, "maxVelocity", 202)
				setVehicleHandling(v, "engineAcceleration", 40.5)
				setVehicleHandling(v, "engineInertia", 50.0)
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 420.0)
				setVehicleHandling(v, "ABS", true)
				setVehicleHandling(v, "driveType", "awd")
				setVehicleHandling(v, "steeringLock", 35.0)
				setVehicleHandling(v, "tractionMultiplier", 1.05)
                setVehicleHandling(v, "tractionLoss", 0.98)
                setVehicleHandling(v, "tractionBias", 0.45)
				setVehicleHandling(v, "suspensionForceLevel", 1.2)
				setVehicleHandling(v, "centerOfMass", { 0.0, -0.15, -0.3})
				setVehicleHandling(v, "dragCoeff",1.0)
				setVehicleHandling(v, "suspensionHighSpeedDamping", 0.1)
			 end	
			 -- Sabre - x
			 if getVehicleModel(v) == 475 then
				setVehicleHandling(v, "maxVelocity", 157)
				setVehicleHandling(v, "engineAcceleration", 25.5)
				setVehicleHandling(v, "engineInertia", 48.0)
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 8.0)
				setVehicleHandling(v, "driveType", "rwd")
				setVehicleHandling(v, "steeringLock", 35.0)
				setVehicleHandling(v, "tractionMultiplier", 0.88)
                setVehicleHandling(v, "tractionLoss", 0.87)
                setVehicleHandling(v, "tractionBias", 0.49)
				setVehicleHandling(v, "suspensionForceLevel", 1.3)
				setVehicleHandling(v, "centerOfMass", { 0.0, -0.15, -0.15})
				setVehicleHandling(v, "suspensionDamping", 0.5)
				setVehicleHandling(v, "suspensionHighSpeedDamping", 2.0)
				setVehicleHandling(v, "mass", 1550)
				setVehicleHandling(v, "turnMass", 3500.0)
			 end	
			 -- Windsor - x
			 if getVehicleModel(v) == 555 then
				setVehicleHandling(v, "maxVelocity", 150)
				setVehicleHandling(v, "engineAcceleration", 33.0)
				setVehicleHandling(v, "engineInertia", 45.0)
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 50.0)
				setVehicleHandling(v, "driveType", "rwd")
				setVehicleHandling(v, "steeringLock", 35.0)
				setVehicleHandling(v, "tractionMultiplier", 0.98)
                setVehicleHandling(v, "tractionLoss", 0.65)
                setVehicleHandling(v, "tractionBias", 0.48)
				setVehicleHandling(v, "dragCoeff",1.5)
				setVehicleHandling(v, "suspensionDamping", 0.5)
				setVehicleHandling(v, "turnMass", 2500.0)
			 end	
			 -- Super GT - x
			 if getVehicleModel(v) == 506 then
				setVehicleHandling(v, "maxVelocity", 245)
				setVehicleHandling(v, "engineAcceleration", 120)
				setVehicleHandling(v, "engineInertia", 50.0)
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 920.0)
				setVehicleHandling(v, "ABS", true)
				setVehicleHandling(v, "driveType", "awd")
				setVehicleHandling(v, "steeringLock", 35.0)
				setVehicleHandling(v, "tractionMultiplier", 1.05)
                setVehicleHandling(v, "tractionLoss", 0.69)
                setVehicleHandling(v, "tractionBias", 0.49)
				setVehicleHandling(v, "suspensionForceLevel", 1.2)
				setVehicleHandling(v, "centerOfMass", { 0.0, -0.15, -0.3})
				setVehicleHandling(v, "dragCoeff",1.0)
				setVehicleHandling(v, "suspensionHighSpeedDamping", 0.1)
			 end	
			 -- ZR-350 - x
			 if getVehicleModel(v) == 477 then
				setVehicleHandling(v, "maxVelocity", 172)
				setVehicleHandling(v, "engineAcceleration", 36.5)
				setVehicleHandling(v, "engineInertia", 50.0)
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 390.0)
				setVehicleHandling(v, "ABS", true)
				setVehicleHandling(v, "driveType", "rwd")
				setVehicleHandling(v, "steeringLock", 35.0)
				setVehicleHandling(v, "tractionMultiplier", 1.11)
                setVehicleHandling(v, "tractionLoss", 0.93)
                setVehicleHandling(v, "tractionBias", 0.40)
				setVehicleHandling(v, "centerOfMass", { 0.0, -0.3, -0.3})
				setVehicleHandling(v, "suspensionDamping", 0.2)
				setVehicleHandling(v, "suspensionForceLevel", 0.95)
				setVehicleHandling(v, "mass", 1500)
				setVehicleHandling(v, "turnMass", 1500)
			 end	
			 -- Vincent x
			 if getVehicleModel(v) == 540 then
				setVehicleHandling(v, "maxVelocity", 158)
				setVehicleHandling(v, "engineAcceleration", 18.0)
				setVehicleHandling(v, "engineInertia", 36.5)
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 15.0)
				setVehicleHandling(v, "driveType", "rwd")
				setVehicleHandling(v, "steeringLock", 35.0)
				setVehicleHandling(v, "tractionMultiplier", 0.92)
                setVehicleHandling(v, "tractionLoss", 0.82)
                setVehicleHandling(v, "tractionBias", 0.52)
				setVehicleHandling(v, "centerOfMass", { 0.0, -0.2, -0.08})
				setVehicleHandling(v, "mass", 1500)
				setVehicleHandling(v, "turnMass", 2500.0)
				setVehicleHandling(v, "suspensionForceLevel", 1.3)
				setVehicleHandling(v, "suspensionDamping", 0.5)
			 end		 
			 -- Sweeper x
			 if getVehicleModel(v) == 574 then
				setVehicleHandling(v, "maxVelocity", 105)
				setVehicleHandling(v, "engineAcceleration", 6.0)
				setVehicleHandling(v, "engineInertia", 30.5)
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 15.0)
				setVehicleHandling(v, "driveType", "rwd")
				setVehicleHandling(v, "steeringLock", 35.0)
				setVehicleHandling(v, "tractionMultiplier", 0.92)
                setVehicleHandling(v, "tractionLoss", 0.82)
                setVehicleHandling(v, "tractionBias", 0.52)
				setVehicleHandling(v, "centerOfMass", { 0.0, -0.2, -0.08})
				setVehicleHandling(v, "mass", 1500)
				setVehicleHandling(v, "turnMass", 2400.0)
				setVehicleHandling(v, "suspensionForceLevel", 1.3)
				setVehicleHandling(v, "suspensionDamping", 0.5)
			 end	
			 -- Elegant x
			 if getVehicleModel(v) == 507 then
				setVehicleHandling(v, "maxVelocity", 167)
				setVehicleHandling(v, "engineAcceleration", 20.0)
				setVehicleHandling(v, "engineInertia", 45.5)
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 17.0)
				setVehicleHandling(v, "driveType", "awd")
				setVehicleHandling(v, "steeringLock", 35.0)
				setVehicleHandling(v, "ABS", true)
				setVehicleHandling(v, "suspensionForceLevel", 2)
			 end	
			 -- Feltzer x
			 if getVehicleModel(v) == 533 then
				setVehicleHandling(v, "maxVelocity", 238)
				setVehicleHandling(v, "engineAcceleration", 64.5)
				setVehicleHandling(v, "engineInertia", 46.0)
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 390.0)
				setVehicleHandling(v, "ABS", true)
				setVehicleHandling(v, "driveType", "awd")
				setVehicleHandling(v, "steeringLock", 35.0)
				setVehicleHandling(v, "tractionMultiplier", 1.51)
                setVehicleHandling(v, "tractionLoss", 0.93)
                setVehicleHandling(v, "tractionBias", 0.36)
				setVehicleHandling(v, "centerOfMass", { 0.0, -0.3, -0.3})
				setVehicleHandling(v, "suspensionDamping", 0.2)
				setVehicleHandling(v, "suspensionForceLevel", 1.05)
				setVehicleHandling(v, "mass", 1550)
			 end	
			 
			-- Tracktor
			if getVehicleModel(v) == 531 then 									
				setVehicleHandling(v, "mass", 2600.0)
				setVehicleHandling(v, "turnMass", 1800)
				setVehicleHandling(v, "dragCoeff", 1.3)
				setVehicleHandling(v, "centerOfMass", { 0.0, 0.1, -0.1 } )
				setVehicleHandling(v, "tractionMultiplier", 1.01)
				setVehicleHandling(v, "tractionLoss", 0.9)
				setVehicleHandling(v, "tractionBias", 0.47)
				setVehicleHandling(v, "numberOfGears", 5)
				setVehicleHandling(v, "maxVelocity", 170)
				setVehicleHandling(v, "engineAcceleration", 20.0)
				setVehicleHandling(v, "engineInertia", 44)
				setVehicleHandling(v, "driveType", "rwd")
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 130.0)
				setVehicleHandling(v, "ABS", true)
				setVehicleHandling(v, "steeringLock", 35.0)
				setVehicleHandling(v, "suspensionForceLevel", 1.4)
				setVehicleHandling(v, "suspensionDamping", 0.2)
				setVehicleHandling(v, "suspensionHighSpeedDamping", 3.0)
				setVehicleHandling(v, "suspensionUpperLimit", 0.28)
				setVehicleHandling(v, "suspensionLowerLimit", -0.10)
				setVehicleHandling(v, "suspensionFrontRearBias", 0.5)
				setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.1)
				setVehicleHandling(v, "modelFlags", 0x40002840)
				setVehicleHandling(v, "handlingFlags", 0x404402)
			end
			 
			 -- Bravura
			 if getVehicleModel(v) == 586 then
				setVehicleHandling(v, "maxVelocity", 164)
				setVehicleHandling(v, "engineAcceleration", 30.0)
				setVehicleHandling(v, "engineInertia", 5.0)
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "driveType", "rwd")
				setVehicleHandling(v, "steeringLock", 35.0)
				setVehicleHandling(v, "tractionMultiplier", 1.8)
                setVehicleHandling(v, "tractionLoss", 1.15)
                setVehicleHandling(v, "tractionBias", 0.5)
				setVehicleHandling(v, "brakeDeceleration", 19.0)
				setVehicleHandling(v, "centerOfMass", { 0.0, 0.0, -0.09})
				setVehicleHandling(v, "dragCoeff",0.0)
			end	
			
			 -- Bravura
			 if getVehicleModel(v) == 468 then
				setVehicleHandling(v, "maxVelocity", 197)
				setVehicleHandling(v, "engineAcceleration", 40.0)
				setVehicleHandling(v, "engineInertia", 5.0)
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "driveType", "rwd")
				setVehicleHandling(v, "steeringLock", 35.0)
				setVehicleHandling(v, "tractionMultiplier", 1.8)
                setVehicleHandling(v, "tractionLoss", 1.15)
                setVehicleHandling(v, "tractionBias", 0.5)
				setVehicleHandling(v, "brakeDeceleration", 19.0)
				setVehicleHandling(v, "centerOfMass", { 0.0, 0.0, -0.09})
				setVehicleHandling(v, "dragCoeff",0.0)
			end	
			  -- FCR-900 - x
		if getVehicleModel(v) == 521 then
				setVehicleHandling(v, "maxVelocity", 168)
				setVehicleHandling(v, "engineAcceleration", 34.0)
				setVehicleHandling(v, "engineInertia", 5.0)
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "driveType", "rwd")
				setVehicleHandling(v, "steeringLock", 35.0)
				setVehicleHandling(v, "tractionMultiplier", 1.8)
                setVehicleHandling(v, "tractionLoss", 1.15)
                setVehicleHandling(v, "tractionBias", 0.5)
				setVehicleHandling(v, "brakeDeceleration", 18.0)
				setVehicleHandling(v, "centerOfMass", { 0.0, 0.0, -0.09})
				setVehicleHandling(v, "dragCoeff",0.0)
			end	
	--end	
end

function loadHandlings()
	for k, v in ipairs(getElementsByType("vehicle")) do
		loadHandling(v)
	end
end
addEventHandler("onResourceStart", getResourceRootElement(getThisResource()), loadHandlings)

function vehicleEnter()
	loadHandling(source)
end
addEventHandler("onVehicleEnter", getRootElement(), vehicleEnter)

-- function resetHandling()
	-- for k, v in ipairs(getElementsByType("vehicle")) do
		-- for k1,v1 in ipairs(setModelHandling(getVehicleModel(v))) do
			-- setVehicleHandling(v, k1, nil)
		-- end
	-- end
-- end
-- addEventHandler("onResourceStop", getResourceRootElement(getThisResource()), resetHandling)